### ISSUE TITLE
cabal2nix should depend on nix-prefetch-scripts

### ISSUE THREAD

**Issue by basvandijk** [NixOS/cabal2nix#106]
I just ran cabal2nix on some URL to a cabal file when I got the following message:

```
cabal2nix: nix-prefetch-zip: createProcess: runInteractiveProcess: exec: 
  does not exist (No such file or directory)
```

After `nix-env -i nix-prefetch-scripts` the error went away.

Shouldn't this be a dependency of `cabal2nix`?

**Comment by phunehehe** [comment]
Also, I notice that `cabal2nix` is available on Hackage, but `nix-prefetch-scripts` is not. This sounds troublesome, as `cabal2nix` from Hackage wouldn't be fully functional. Or did I miss something?

**Comment by peti** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/019b18722d1c7f2bcdb296c907a5a8d2ee9c1401.

**Comment by basvandijk** [comment]
Thanks!
