### ISSUE TITLE
darcs support

### ISSUE THREAD

**Issue by timsears** [NixOS/cabal2nix#113]
Any plans to support darc in addition to git, svn, et al?

**Comment by bennofs** [comment]
@timsears If you want to work on this, here are some pointers what needs to be done:

1. Add a nix-prefetch-darcs script that works like all the other nix-prefetch-* scripts (and add it to the nix-prefetch-scripts package in nixpkgs)
2. Add "darcs" to the list of supported VCS in https://github.com/NixOS/cabal2nix/blob/master/src/Distribution/Nixpkgs/Fetch.hs#L72-L78
