### ISSUE TITLE
Generate nix-parsable data instead of complete expressions

### ISSUE THREAD

**Issue by shlevy** [NixOS/cabal2nix#116]
Currently, `cabal2nix` takes the data in the cabal files and turns it into a full derivation. This is problematic because sometimes that information is incomplete/incorrect (e.g. a non-haskell dep is not represented, or a version upper bound is too strict), but because the entire build expression is generated the only way to fix the error is to modify `cabal2nix`.

Instead, I propose that `cabal2nix` simply generate a file (perhaps JSON, so that it's not even nix specific) that contains all of the information that nix cares about. Then, by default the cabal builder would take that information and do the build as it is done now, but we could easily add a way to override those things without modifying the data file (and there would never be any reason to manually modify the data file at all)

**Comment by jwiegley** [comment]
+1

**Comment by peti** [comment]
Have you seen what expressions look like in the haskell-ng branch? I.e. https://raw.githubusercontent.com/peti/nixpkgs/haskell-ng/pkgs/development/haskell-modules/hackage-packages.nix?

**Comment by peti** [comment]
Using `overrideCabal` from https://github.com/peti/nixpkgs/blob/haskell-ng/pkgs/development/haskell-modules/lib.nix, one can write:

    overrideCabal foo (drv: { buildDepends = drv.buildDepends or [] ++ [bar]; }); 

Simply override the `mkDerivation` function with one that transforms the derivation before calling the real one. This nests fine, too. I do this all over the place in https://github.com/peti/nixpkgs/blob/haskell-ng/pkgs/development/haskell-modules/configuration-common.nix.

**Comment by shlevy** [comment]
OK. I still think separating out "this is the data parsed automatically from hackage" from "this is how we turn the data into a package" makes sense, but `overrideCabal` seems good enough that if you disagree we can close this.

**Comment by peti** [comment]
I'm not sure what exactly you want it is that you want to do. Can you maybe describe a concrete example of package data in the format you'd like and explain a brief use-case for that stuff that cannot be covered with the current approach?

**Comment by shlevy** [comment]
So instead of:

```nix
  "3d-graphics-examples" = callPackage
    ({ mkDerivation, base, GLUT, OpenGL, random }:
     mkDerivation {
       pname = "3d-graphics-examples";
       version = "0.0.0.0";
       sha256 = "1v2zv94npviggqfqabfzp7ab54nnw9wdb60y20f1lzw13an0a14q";
       isLibrary = false;
       isExecutable = true;
       buildDepends = [ base GLUT OpenGL random ];
       homepage = "http://darcs.wolfgang.jeltsch.info/haskell/3d-graphics-examples";
       description = "Examples of 3D graphics programming with OpenGL";
       license = stdenv.lib.licenses.bsd3;
     }) {};
```

we'd have something like

```nix
  "3d-graphics-examples" = {
     pname = "3d-graphics-examples";
     version = "0.0.0.0";
     sha256 = "1v2zv94npviggqfqabfzp7ab54nnw9wdb60y20f1lzw13an0a14q";
     isLibrary = false;
     isExecutable = true;
     haskellBuildDependencies = [ "base" "GLUT" "OpenGL" "random" ];
     homepage = "http://darcs.wolfgang.jeltsch.info/haskell/3d-graphics-examples";
     description = "Examples of 3D graphics programming with OpenGL";
     license = "BSD3"; # Whatever the literal string in the .cabal file is
  };
```

The latter is pure data (could be represented without loss in JSON even), and we can use that data however we want in nixpkgs without having to modify cabal2nix at all. The former gives us a more restricted interface without much gain.

**Comment by shlevy** [comment]
Also, the `pname` attribute can be dropped in my latter example.

**Comment by jwiegley** [comment]
It's also possible if we go this route that instead of having one file per Hackage entry, we could have one gigantic generated JSON file containing, and then one Nix file per package that we actually need to override details for.

This would allow us to very easily have separate JSON data sets for each release of Stackage, for example, giving Nix users a more stable package source to install packages from (since the version numbers there would not change as `nixpkgs` progresses).

**Comment by shlevy** [comment]
@jwiegley I believe it's all in one file in `haskell-ng` already

**Comment by shlevy** [comment]
@peti one more point in favor of the pure data approach: issues like #116 become moot, because cabal2nix doesn't need to care if something is a core package or not

**Comment by peti** [comment]
@shlevy, okay, it's no big deal to generate that format. What is the use case?

**Comment by shlevy** [comment]
The use case is a) to avoid having to put any non-generic information into `cabal2nix` (e.g. a list of core packages, or overridden native dependencies) and, more minorly, b) to reduce the need for complicated overriding (e.g. rather than call the cabal builder and then override the results, we can simply directly modify the arguments to the cabal builder if that call is separate)

Also, I don't personally care about this, but written the way I proposed this information could be used by wildly divergent haskell package set implementations, including those written in something besides nix.

**Comment by peti** [comment]
Cabal2nix contains virtually no package-specific know-how in the 2.x branch, and what little information remains is going to go away soon once I have the time to clean up.

Overriding couldn't be simpler than it already is, IMHO. The `overrideCabal` function is quite straightforward, and it can be wrapped in other convenience functions that specialize cases like "jailbreak", "notest", "nohaddock", "enableFlag", "disableFlag", etc. I don't see how a format change in `hackage-packages.nix` could have any further positive effect compared to the current state. If you can give me an example that demonstrates how a new scheme might look like compared to the current one?

**Comment by shlevy** [comment]
Hmm I'm not sure how to explain further, and `overrideCabal` seems like it covers the 95% of what I care about, so I'll close this until/unless I can come up with something more concrete.
