### ISSUE TITLE
Include git revision from hackage2nix and all-cabal-files repositories in the generated hackage-packages.nix file

### ISSUE THREAD

**Issue by peti** [NixOS/cabal2nix#134]
This allows us to track which "version" the file was generated from.

**Comment by ocharles** [comment]
I think it would be worth stamping the cabal2nix version, too.

**Comment by peti** [comment]
I agree. The tricky bit is that I'd like to have the version from `git describe` rather than Cabal, because I don't edit my Cabal file every time I commit. (Maybe [Cartel](http://hackage.haskell.org/package/cartel) will solve this issue for me, but I'm not decided yet.)

**Comment by peti** [comment]
We no longer use Hackage as an input. Instead, our Cabal files come from https://github.com/commercialhaskell/all-cabal-files, which provides stable version identifiers.

**Comment by peti** [comment]
Implemented in c84f676.
