### ISSUE TITLE
Support custom flags

### ISSUE THREAD

**Issue by michalpalka** [NixOS/cabal2nix#135]
It would be nice if arbitrary flags could be enabled/disabled when processing a cabal package. I couldn't find a way of doing it, so I raise it in this issue.

**Comment by peti** [comment]
<https://github.com/NixOS/cabal2nix/blob/master/src/Cabal2Nix/Flags.hs>?

**Comment by michalpalka** [comment]
Sorry, I should have been more specific. I have a local package, and did not feel that patching Flags.hs is a good idea. Of course if the authors of cabal2nix think it is, it will probably work fine for me.

**Comment by peti** [comment]
I'm not sure whether I understand your use-case correctly. What exactly is it that you'd like to
achieve? Does the expression generated by cabal2nix not work for you? Can you give me a specific
example to illustrate the problem you're trying to solve?

**Comment by michalpalka** [comment]
I have custom software, which comes as a cabalised package. The package has a UseX flag, which is disabled by default, and adds some dependencies in addition to functionality. I want to create a nix expression, which would include these additional dependencies. To do it I could edit the Flags.hs (or patch it), but I expected that this also can be done without editing it.

**Comment by peti** [comment]
The current version from Git now accepts flags on the command line. I'll bump the `haskellngPackages.cabal2nix` attribute accordingly in a minute or two.
