### ISSUE TITLE
pango should depend on both pkgs.cairo and haskell cairo

### ISSUE THREAD

**Issue by bergey** [NixOS/cabal2nix#137]
At present, `hackage-packages.nix` has an override to `pkgs.cairo`, and the haskell package is not included in the dependencies.  So `./Setup configure` reports:

```
Configuring pango-0.13.0.5...
setup: At least the following dependencies are missing:
cairo >=0.13.0.0 && <0.14
``` 

Sorry if this is the wrong place to report this.  I'm using haskell-ng for the first time today, and I'm not sure how it fits together yet.

**Comment by peti** [comment]
This is a result of this bug: https://github.com/NixOS/cabal2nix/issues/136. I've committed a fix for the build error in https://github.com/NixOS/nixpkgs/commit/4ab133a that remedies the issue until the underlying problem in `hackage2nix` is fixed. The `pango` build should now succeed fine.

Thank you for the bug report!

**Comment by bergey** [comment]
Thank you for the quick response, and the links!
