### ISSUE TITLE
cabal2nix --shell output doesn't have the overrides that are generated for hackage-packages.nix

### ISSUE THREAD

**Issue by abbradar** [NixOS/cabal2nix#144]
Following https://github.com/NixOS/cabal2nix/issues/107 -- while `hackage4nix` now does the correct thing overriding system libraries, packages generated by `cabal2nix` are still suffering from this issue. We can just add the same override from `pkgs` to the generated package as `hackage4nix` does to fix this -- I don't know how different that is to implement, though.

**Comment by peti** [comment]
I'm not sure whether I understand what you mean. `cabal2nix` generates a function that takes the required build inputs as arguments. There are no overrides, because no code is generated that calls this function -- unless you're referring to the `--shell` output?

**Comment by abbradar** [comment]
Oh, yes, I referred to it -- sorry. However, after some thoughts, overriding needed things right in the generated expression would also be good -- at the point of generation `cabal2nix` knows that this is a non-haskell dependency and can do something about it, and if not, you would have to override them by hand later peeking into the .cabal file.

**Comment by peti** [comment]
The difference between `hackage2nix` and `cabal2nix` is that the former tool generates output only for Hackage package and that it depends on `~/.cabal/packages/hackage.haskell.org/00-index.tar` being available -- a complete database of all known packages. This information allows `hackage2nix` to generate those overrides. `cabal2nix`, on the other hand, doesn't have such a restrictude use-case; it can be used to generate build instructions for all kinds of private packages that may have other (private) Haskell dependencies that Hackage doesn't know about, etc. I don't think it's possible to generate overrides within `cabal2nix` that have the same quality as those generated by `hackage2nix`. I agree that it would be nice to have that option available, though.

**Comment by abbradar** [comment]
Oh, I understand the restriction now -- it really is so, then. I just had an idea though. With a patch[1] to nixpkgs we can do:
```
  extraLibraries = with defaultScope; [ python ncurses ];
```
and we would have exactly the same scoping as callPackage. How does this sound?

[1]: https://github.com/abbradar/nixpkgs/commit/42ab1ba3bf378d93e4fddfbcffb539a841f407cc

**Comment by abbradar** [comment]
(N.B.: I don't know why `defaultScope` was not inherited into `pkgs` set previously; maybe it was done on purpose)

**Comment by peti** [comment]
`python` and `ncurses` are arguments of the generated function. That `with` statement is not going to have any effect inside of the function body.

**Comment by abbradar** [comment]
Ouch, I've forgotten about our scoping rules w.r.t. `with`. Well, I've already tried to invent something like this in #107 to no avail ^_^. Do we want to keep this open as a reminder for a possible enhancement?

**Comment by peti** [comment]
Yes, let's keep the ticket open just in case someone has a brilliant idea. :smile:

**Comment by np** [comment]
I'm not sure if this is really related but I wish to extend my shell.nix which comes from cabal2nix --shell. I want to include specific dependencies to tools like git or whatever I need.

**Comment by peti** [comment]
It finally occurred to me that `cabal2nix` cannot generate those overrides, because it operates on a single package. `hackage2nix` generates the entire package set -- so it knows which names exist and might conflict with system packages, etc., but `cabal2nix` doesn't have that information. I believe that we'll have to live with the current status quo (which doesn't seem so bad, really).

**Comment by np** [comment]
Ok, my setup is now the following, which I'm describing here to help improving the documentation.

Example with Agda:

Agda.nix is exactly the output of `cabal2nix .`
default.nix is where I apply the overrides:

```
$ cat default.nix
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc7101" }:
(nixpkgs.pkgs.haskell.packages.${compiler}.override {
    overrides = self: super: {
      QuickCheck = self.callPackage ./nix/QuickCheck.nix {};
      zlib       = self.callPackage ./nix/zlib.nix { inherit (nixpkgs.pkgs) zlib; };
    };
  }
).callPackage ./Agda.nix {}
```

These two files are generated as usual:

```
cabal2nix cabal://QuickCheck-2.8.1 > nix/QuickCheck.nix
cabal2nix cabal://zlib-0.5.4.2 > nix/zlib.nix
```

Finally the shell.nix is as follows:

```
$ cat shell.nix
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc7101" }:
nixpkgs.lib.overrideDerivation
  (import ./default.nix { inherit nixpkgs compiler; }).env
  (old:
   { buildInputs = old.buildInputs ++
       (with nixpkgs.haskell.packages.${compiler}; [
       cabal-install
     # more deps can go here
    ]);})
```
