### ISSUE TITLE
cannot parse output from nix-prefetch-git any more

### ISSUE THREAD

**Issue by peti** [NixOS/cabal2nix#150]
Apparently, the output of `nix-prefetch-git` has changed in `master` recently:

    $ cabal2nix git://github.com/peti/hackage-db.git
    curl: (1) Protocol "git" not supported or disabled in libcurl
    error: could not download git://github.com/peti/hackage-db.git
    curl: (1) Protocol "git" not supported or disabled in libcurl
    /run/current-system/sw/bin/nix-prefetch-url: download of ‘git://github.com/peti/hackage-db.git’ failed
    Initialized empty Git repository in /tmp/git-checkout-tmp-n743E419/git-export/.git/
    remote: Counting objects: 15, done.
    remote: Compressing objects: 100% (12/12), done.
    remote: Total 15 (delta 1), reused 9 (delta 0), pack-reused 0
    Unpacking objects: 100% (15/15), done.
    From git://github.com/peti/hackage-db
     * branch            HEAD       -> FETCH_HEAD
    Switched to a new branch 'fetchgit'
    git human-readable version is -- none --
    removing `.git'...
    *** unexpected output from nix-prefetch-git script: 
    git revision is 0b32fe92f54a607c780b8c4674f359ce63d599bd
    Commit date is 2015-01-15 21:41:08 +0100
    214030ce5794b6684d6a5b3ad49538b42492f206a1186e95aeba70cdc38c98db
    /nix/store/x8lpilh6bbsqnqwh1v88ix24l72bgkv4-git-export

Cc: @bennofs

**Comment by sdx23** [comment]
This is still an issue:

    % cabal2nix git://github.com/peti/hackage-db.git
    curl: (1) Protocol "git" not supported or disabled in libcurl
    error: could not download git://github.com/peti/hackage-db.git
    curl: (1) Protocol "git" not supported or disabled in libcurl
    /usr/bin/nix-prefetch-url: download of ‘git://github.com/peti/hackage-db.git’ failed
    Initialized empty Git repository in /tmp/user/1001/git-checkout-tmp-bhDQMwPS/git-export/.git/
    remote: Counting objects: 15, done.
    remote: Compressing objects: 100% (12/12), done.
    remote: Total 15 (delta 1), reused 9 (delta 0), pack-reused 0
    Unpacking objects: 100% (15/15), done.
    From git://github.com/peti/hackage-db
     * branch            HEAD       -> FETCH_HEAD
    fatal: unable to look up current user in the passwd file: no such user
    remote: Counting objects: 190, done.
    remote: Compressing objects: 100% (78/78), done.
    remote: Total 190 (delta 69), reused 186 (delta 67), pack-reused 0
    Receiving objects: 100% (190/190), 29.95 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (69/69), done.
    fatal: unable to look up current user in the passwd file: no such user
    Unable to checkout HEAD from git://github.com/peti/hackage-db.git.
    abort: repository git://github.com/peti/hackage-db.git not found!
    svn: E170000: Unrecognized URL scheme for 'git://github.com/peti/hackage-db.git'
    failed to open trace file: [Errno 2] No such file or directory: ':/.bzr.log'
    bzr: ERROR: Unsupported protocol for url "git://github.com/peti/hackage-db.git"
    *** failed to fetch source. Does the URL exist?

However:

    % git clone git://github.com/peti/hackage-db.git
    Cloning into 'hackage-db'...
    remote: Counting objects: 195, done.
    remote: Total 195 (delta 0), reused 0 (delta 0), pack-reused 195
    Receiving objects: 100% (195/195), 29.52 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (74/74), done.
    Checking connectivity... done

**Comment by peti** [comment]
I cannot reproduce that problem. This is what I get using `cabal2nix` from the current Nixpkgs `master` branch:

~~~~
$ /nix/store/rcznfasn0gpgznaqnb82y25mim0mw3fh-cabal2nix-20151217/bin/cabal2nix git://github.com/peti/hackage-db.git
curl: (1) Protocol "git" not supported or disabled in libcurl
error: could not download git://github.com/peti/hackage-db.git
downloading ‘git://github.com/peti/hackage-db.git’... 
error: unable to download ‘git://github.com/peti/hackage-db.git’: Unsupported protocol (1)
Initialized empty Git repository in /tmp/git-checkout-tmp-cE6rWCcY/git-export/.git/
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 15 (delta 1), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.
From git://github.com/peti/hackage-db
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
git human-readable version is -- none --
removing `.git'...
hash is 21e77d2a9da9c74a8cd6e8f4a06e16a77c5459c66aad6d7594ac166c357245a5
path is /nix/store/x01901nsv6cdkarbhzivsgcg2qfmm8sh-git-export
{ mkDerivation, base, bytestring, Cabal, containers, directory
, fetchgit, filepath, stdenv, tar, utf8-string
}:
mkDerivation {
  pname = "hackage-db";
  version = "1.23";
  src = fetchgit {
    url = "git://github.com/peti/hackage-db.git";
    sha256 = "21e77d2a9da9c74a8cd6e8f4a06e16a77c5459c66aad6d7594ac166c357245a5";
    rev = "5f8eafdca13553f3a16d245caaeb3deb35e470d6";
  };
  libraryHaskellDepends = [
    base bytestring Cabal containers directory filepath tar utf8-string
  ];
  homepage = "http://github.com/peti/hackage-db";
  description = "access Hackage's package database via Data.Map";
  license = stdenv.lib.licenses.bsd3;
~~~~

**Comment by bennofs** [comment]
The problem seems to be this line:

    fatal: unable to look up current user in the passwd file: no such user
    Unable to checkout HEAD from git://github.com/peti/hackage-db.git.

@sdx23 Can you check if `nix-prefetch-git git://github.com/peti/hackage-db.git` works? (you can get the `nix-prefetch-git` executable from `nixpkgs.nix-prefetch-scripts`)

**Comment by sdx23** [comment]
@bennofs It doesn't. Fails with the same messages. We got a setup with sssd here, which seems to be related to this issue. There is, however, no reason for it to lookup any user since it's an anonymous checkout.

**Comment by peti** [comment]
I suppose it might be a good idea to report this issue in the https://github.com/NixOS/nixpkgs repository where it is more likely to be discovered by people who are / feel responsible for `nix-prefetch-git`.
