### ISSUE TITLE
--shell produces "error: attribute ‘env’ missing"

### ISSUE THREAD

**Issue by andremarianiello** [NixOS/cabal2nix#151]
I checked out a github repo containing a haskell library (attoparsec if it matters) and ran

    cabal2nix --shell . > shell.nix && nix-shell

and get the following error

    error: attribute ‘env’ missing, at "/path/to/shell.nix":23:3

I have a hard time believing this is a bug because I figure someone would have caught it and it's easily fixable (by removing ".env" from "pkg.env" on the last line). So what am I doing wrong here?

**Comment by peti** [comment]
I don't believe that `nix-shell` is intended to be used that way in a pipe. Instead, you should probably run:

    cabal2nix --shell . >shell.nix && nix-shell

**Comment by andremarianiello** [comment]
Oh right sorry. I'm getting the same error. I'll edit the original comment.

**Comment by peti** [comment]
What version of `cabal2nix` do you have? Did you install 'haskellngPackages.cabal2nix`?

**Comment by andremarianiello** [comment]
2.0. And yes, I believe I installed it from haskellngPackages.

**Comment by peti** [comment]
Please paste the output from `cabal2nix --shell .`.

**Comment by peti** [comment]
When I try this, it works just fine:

    [simons@latitude:/tmp]$ git clone https://github.com/bos/attoparsec
    Cloning into 'attoparsec'...
    remote: Counting objects: 3731, done.
    remote: Total 3731 (delta 0), reused 0 (delta 0), pack-reused 3731
    Receiving objects: 100% (3731/3731), 882.52 KiB | 1007.00 KiB/s, done.
    Resolving deltas: 100% (1974/1974), done.
    Checking connectivity... done.

    [simons@latitude:/tmp]$ cd attoparsec/

    [simons@latitude:/tmp/attoparsec]$ cabal2nix --shell . >shell.nix

    [simons@latitude:/tmp/attoparsec]$ nix-shell 
    these derivations will be built:
      /nix/store/pjksp85bi5jn7knb8z642m6fpvq31n5v-ghc-7.8.4.drv
    these paths will be fetched (0.00 MiB download, 0.56 MiB unpacked):
      /nix/store/xgh42ggv38r039nhyii1n74dzcvv4c23-haskell-quickcheck-unicode-1.0.0.0
    fetching path ‘/nix/store/xgh42ggv38r039nhyii1n74dzcvv4c23-haskell-quickcheck-unicode-1.0.0.0’...

    *** Downloading ‘http://hydra.cryp.to/nar/xgh42ggv38r039nhyii1n74dzcvv4c23-haskell-quickcheck-unicode-1.0.0.0’ to ‘/nix/store/xgh42ggv38r039nhyii1n74dzcvv4c23-haskell-quickcheck-unicode-1.0.0.0’...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 72728    0 72728    0     0   102k      0 --:--:-- --:--:-- --:--:--  102k

    building path(s) ‘/nix/store/19qpk94va45mbm7v58k7hig87vlxp009-ghc-7.8.4’
    created 130 symlinks in user environment

    [nix-shell:/tmp/attoparsec]$

**Comment by andremarianiello** [comment]
```
with (import <nixpkgs> {}).pkgs;
let pkg = haskellngPackages.callPackage
            ({ mkDerivation, array, base, bytestring, containers, deepseq
             , QuickCheck, quickcheck-unicode, scientific, stdenv
             , test-framework, test-framework-quickcheck2, text, vector
             }:
             mkDerivation {
               pname = "attoparsec";
               version = "0.12.1.3";
               src = ./.;
               buildDepends = [
                 array base bytestring containers deepseq scientific text
               ];
               testDepends = [
                 array base bytestring deepseq QuickCheck quickcheck-unicode
                 scientific test-framework test-framework-quickcheck2 text vector
               ];
               homepage = "https://github.com/bos/attoparsec";
               description = "Fast combinator parsing for bytestrings and text";
               license = stdenv.lib.licenses.bsd3;
             }) {};
in
  pkg.env
```

What does yours look like?

**Comment by peti** [comment]
Are you sure that `$NIX_PATH` points to the `master` branch an your system? Haskell NG is not available in `14.12` or any other release branch yet.

**Comment by peti** [comment]
My `shell.nix` file is identical.

**Comment by andremarianiello** [comment]
So am I using a wrong version of cabal2nix?

**Comment by peti** [comment]
See my comment above about `$NIX_PATH`.

**Comment by andremarianiello** [comment]
I have checked out the nixpkgs repo locally, but I don't remember if I installed cabal2nix from there or from a channel. My `$NIX_PATH` looks like this:

```
 echo $NIX_PATH
/nix/var/nix/profiles/per-user/root/channels/nixos:nixpkgs=/etc/nixos/nixpkgs:nixos-config=/etc/nixos/configuration.nix
```

**Comment by peti** [comment]
What do `nix-instantiate --eval --strict -E '<nixpkgs>'` and `nix-channel --list` say on your system?

**Comment by andremarianiello** [comment]
```
nix-instantiate --eval --strict -E '<nixpkgs>'
/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

and

```
 nix-channel --list
nixos-14.12 https://nixos.org/channels/nixos-14.12
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

**Comment by peti** [comment]
Well, this means that `<nixpkgs>` expands to version `nixos-14.12` of the package set -- not to the `master` branch. Try adding `-I nixpkgs=/foo` to the `nix-shell` command line where `/foo` is the full path to your locally checked-out Nixpkgs  repository.

**Comment by andremarianiello** [comment]
Okay, that seems to have worked. I have a couple questions now. 

1) Was the issue that my cabal2nix installation was "newer" than the dependencies I was using?

2) What is the best way to fix this without having to manually specify a path to my local nixpkgs repo every time?

**Comment by peti** [comment]
The issue was that `nix-shell` evaluates the generated `shell.nix` file in a package set that's too old, i.e. the one from the `nixos-14.12` branch. To change that permanently, you can configure your `$NIX_PATH` to point to the proper repository. The `nix-shell` man page has a detailed explanation of that variable (and of the `-I` flag).

**Comment by andremarianiello** [comment]
Alright, thank you very much for your help.
