### ISSUE TITLE
Use specific cabal revision for jailbreaking

### ISSUE THREAD

**Issue by purefn** [NixOS/cabal2nix#154]
I may be misunderstanding again, but it appears that `editedCabalFile` meant to work around the mutability of cabal metadata on Hackage.  But it falls short because it still downloads the cabal file from `http://hackage.haskell.org/package/${pname}-${version}/${pname}.cabal`, which could be changed after the `hackage-packages.nix` file is generated. To more fully fix this it would be better if `cabal2nix` parsed the `x-revision` field from the cabal file served by Hackage and that was made part of the derivation. Then the specific version of the cabal file can be downloaded from `https://hackage.haskell.org/package/${pname}-${version}/revision/${revision}.cabal`. 

If this is generally agreed to be the right solution, I'm happy to submit PRs.

**Comment by peti** [comment]
This issue has been addressed in https://github.com/NixOS/nixpkgs/issues/6914.

**Comment by purefn** [comment]
Fantastic!
