### ISSUE TITLE
Unknown license BSD2

### ISSUE THREAD

**Issue by shlevy** [NixOS/cabal2nix#161]
```
$ ./result/bin/hackage2nix > hackage.nix
hackage2nix: Cabal2Nix.License.fromCabalLicense: unknown license BSD2
hackage2nix: thread blocked indefinitely in an MVar operation
```

FWIW I see `fromCabalLicense (UnknownLicense "BSD2")                = Known "stdenv.lib.licenses.bsd2"` so I'm not sure why it's choking there.

**Comment by peti** [comment]
What does the `cabal configure -v` output look like on your system? I'm particularly interested in the Cabal version you're using.

**Comment by shlevy** [comment]
$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library
