### ISSUE TITLE
Irrefutable pattern failure `Just pkgId`

### ISSUE THREAD

**Issue by dmjio** [NixOS/cabal2nix#172]
Getting a partial function pattern match failure when using the command below. It looks like I added `.cabal` to the end accidentally. Maybe we should make the error more intelligent. If you agree, I can make a pull.
```
λ Davids-MacBook-Pro foooba → cabal2nix cabal://ses-html.cabal --sha256 blah > default.nix
cabal2nix: src/Cabal2Nix/Package.hs:53:3-30: Irrefutable pattern failed for pattern Just pkgId
```

It seems to come from this line: 
https://github.com/NixOS/cabal2nix/blob/master/src/Cabal2Nix/Package.hs#L53
```haskell
 where
  Just pkgId = simpleParse pkg
```

It seems like failure is a correct choice here, but maybe we could make it a little more intelligent. 
```
where
  pkgId = fromMaybe (error "Couldn't find package") (simpleParse pkg)
```

**Comment by peti** [comment]
Thank you very much for the suggestion!
