### ISSUE TITLE
There is a mistake in user-guide.md

### ISSUE THREAD

**Issue by amitai-hoze** [NixOS/cabal2nix#179]
It says there `cabal-install`, and should say `cabalInstall` instead..

**Comment by peti** [comment]
No attribute `cabalInstall` exists in current versions of Nixpkgs:

~~~~~
$ grep -R cabalInstall pkgs/
pkgs/development/compilers/ghcjs/ghcjs.patch:@@ -1085,8 +1076,11 @@ cabalInstallFlags parmakeGhcjs = do

$ 
~~~~~~

That name is still active in old release branches, but has been removed in `master` a while ago.
