### ISSUE TITLE
cabal2nix doesn't like numbers in names

### ISSUE THREAD

**Issue by Warbo** [NixOS/cabal2nix#180]
I'm working on a project which just so happens to auto-generate Cabal projects of the following form:

```
name: mlspec-temp-1298503453
version: 1
build-type: Simple
category: Testing
maintainer: nobody@example.com
synopsis: Auto-generated by MLSpec
description: Auto-generated by MLSpec
license: PublicDomain
cabal-version: >= 1.2
executable Main
  build-depends: directory, base >= 4.8 && < 4.9, quickspec < 2
  main-is: Main.hs
```

This seems valid accoring to https://www.haskell.org/cabal/users-guide/developing-packages.html#package-names-and-versions

> Cabal package names can use letters, numbers and hyphens, but not spaces.

However, cabal2nix complains:

```
$ cabal2nix ./.
*** error parsing cabal file: 1: Parse of field 'name' failed.
```

If I change the last "section" of the name to contain a letter, ie. `name: mlspec-temp-a1298503453`, it works:

```
$ cabal2nix ./.
{ mkDerivation, base, directory, quickspec, stdenv }:
mkDerivation {
  pname = "mlspec-temp-a1298503453";
  version = "1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ base directory quickspec ];
  description = "Auto-generated by MLSpec";
  license = stdenv.lib.licenses.publicDomain;
}
```

I have no problem working around this by changing my naming convention, but thought I'd raise an issue in case anyone hits it in the future (eg. with a more sensible package name like `foo-2`).

**Comment by peti** [comment]
The name `mlspec-temp-1298503453` is not a valid package name, and Cabal will not parse it. The following program accepts the string as a package identifier (i.e. package name + version), but if you try to parse it as a `PackageName`, then you'll get an error.

~~~~~ Haskell
import Distribution.Package
import Distribution.Text

pkgid :: Maybe PackageIdentifier
pkgid = simpleParse "mlspec-temp-1298503453"

main = print pkgid
~~~~~

As such, the behavior of `cabal2nix` seems quite reasonable. Am I missing something?

**Comment by Warbo** [comment]
> The name mlspec-temp-1298503453 is not a valid package name, and Cabal will not parse it.

Ah OK then, the bug is in Cabal's documentation, so I'll close this. Thanks :)
