### ISSUE TITLE
hackage2nix maintainer field

### ISSUE THREAD

**Issue by jb55** [NixOS/cabal2nix#193]
I want to make sure I get an email when my packages break during CI, is there any way to opt in to those?

**Comment by peti** [comment]
That is a good point. Currently, there is no way to opt in to those messages. I'll figure out some config file for `hackage2nix` to make that happen.

**Comment by peti** [comment]
The procedure to get yourself added as a maintainer is as follows:

1. Get yourself added to https://github.com/NixOS/nixpkgs/blob/master/lib/maintainers.nix.
2. Add an entry for yourself to https://github.com/NixOS/cabal2nix/blob/master/src/Distribution/Nixpkgs/Haskell/FromCabal/Configuration/Maintainers.hs and list all the packages you'd like to maintain.
