### ISSUE TITLE
language-nix needs merge with an old library or renaming

### ISSUE THREAD

**Issue by abbradar** [NixOS/cabal2nix#204]
While looking at https://github.com/NixOS/nixpkgs/issues/9751 I wanted to use `language-nix` library from Hackage, which provides parsing and simple evaluation of Nix expressions. However I was very confused to find that `language-nix` in NixOS points to basically another library without needed features. We have several options:

1. Merge libraries, adding functions from the old one to the new one.
2. Rename old library, keep new library.
3. Rename new library, keep old library.
4. Something else?...

How should we proceed?

**Comment by peti** [comment]
The `language-nix` library from this repository will replace the one that's currently on Hackage, i.e. this source code will move to https://github.com/peti/language-nix and to Hackage eventually. I just haven't gotten around to it. The library that's currently released as `language-nix` on Hackage doesn't work very well. I've found that using Parsec for parsing Nix leads into a dead end, or rather, into code that is weird and hard to understand.

I'm not sure what the best short-term solution is. I could make a release of this code to Hackage quickly to make it clear that the old library is deprecated. Does that sound okay?

**Comment by abbradar** [comment]
Yeah, sounds good. I've also decided that JSON would be a better medium for my needs so count me out of the "needs all the old features right now" list ^_^.

**Comment by peti** [comment]
http://hackage.haskell.org/package/language-nix
