### ISSUE TITLE
stack2nix?

### ISSUE THREAD

**Issue by proger** [NixOS/cabal2nix#212]
I was trying to use nixpkgs to build a stack-based program and ended up with [an ugly hack that selectively parses stack.yaml and runs cabal2nix a couple of times](https://gist.github.com/proger/15f5dbfd8a0f5124b1d9). Do you think cabal2nix should support stack files?

**Comment by peti** [comment]
It sure would be nice if it did.

**Comment by domenkozar** [comment]
I might give this a go soonish. https://github.com/commercialhaskell/stack/blob/master/src/Stack/Config.hs#L224 is a good starting point.

**Comment by bennofs** [comment]
I plan to work on this, including support for generating the correct stackage snapshot package set on the fly.

**Comment by domenkozar** [comment]
@bennofs let's collaborate this is also on my todo

**Comment by bennofs** [comment]
@domenkozar WIP implemention of stackage2nix at https://github.com/bennofs/cabal2nix/tree/feature-stackage2nix. Successfully generates a haskell-packages.nix for latest stackage LTS, but I need to do some more testing before I can submit that as a proper PR

**Comment by bennofs** [comment]
For stack2nix, I would use that to first generate a packages.nix for the snapshot specified in the stack file and then generate the necessary overrides for stack's extra packages

**Comment by domenkozar** [comment]
IIRC cabal2nix used to have stackage2nix.

**Comment by bennofs** [comment]
@domenkozar yeah but that was a hack using some sed magic. I want an exact stackage2nix so it 100% matches what stack would build (modulo nix-specific configure options to help find libraries, but that should be everything that is different)

**Comment by peti** [comment]
Initially, we *did* take the Cabal flags from Stackage, but ultimately dropped that feature again and relied on auto-detection henceforth. Keep in mind that Stackage builds *only* on Linux/x86_64 running Ubuntu. Nixpkgs, however, may run on 32 bit Linux as well as Darwin etc., so the flags given by Stackage sometimes don't fit. On some occasions, the flags fit but we don't want them anyway, i.e. in case of `git-annex`. Stackage can't buid the full version because some dependencies aren't in Stackage. We can (and want to) build the full version, however.

**Comment by bennofs** [comment]
@peti well I understand that this makes sense for hackage-packages.nix, but if you want to use the snapshot to build packages with a stack.yaml, then those packages probably expect git-annex not to be the full version (because they build against Stackage with stack)

**Comment by bennofs** [comment]
@peti I was under the impression that stack also used these flags when it builds against a stackage snapshot. So apparently, it doesn't do that?

**Comment by peti** [comment]
I haven't actually investigated this issue, so I can't say for sure. My impression was that the flags recorded in the build plan are simply whatever Cabal auto-detected during the test builds on Travis. I may be wrong though.

**Comment by domenkozar** [comment]
@bennofs did you check how hard would it be to ask stack for the final build plan and then get a list of packages with versions? Using that we could generate the package set.

**Comment by bennofs** [comment]
@domenkozar that's a good idea. But I would have to look into stack's source code to understand how exactly stack does build plan construction internally and if retains enough information for us.

**Comment by domenkozar** [comment]
I think it's worth seeing how easy is that.

**Comment by bennofs** [comment]
@domenkozar I think I dealbreaker here is how stack handles `git` dependencies: it'll check them out before resolving dependencies, which is not viable for generating nix expressions (the generation should be free of network accesses, so it works in import-from-derivation as well. Any git-dependencies should be fetched using `fetchgit`)

**Comment by domenkozar** [comment]
Maybe we could ask @snoyberg for a video call to talk about how stack works and how to best integrate with it.

**Comment by puffnfresh** [comment]
I started doing something like this a while ago, I got some information from Stack being put into derivations:

https://github.com/puffnfresh/stack/tree/feature/full-nix

**Comment by domenkozar** [comment]
So we're talking about two use cases here:

1) `stack --full-nix` which would actually use nix for building and could use binary cache

2) Generating Nix expressions to be used outside stack

Both are really useful! @puffnfresh how  far did you get on 1)?

**Comment by 4e6** [comment]
@bennofs `stackage2nix` looks good. I tested it with the following `nixpkgs` fork: 
https://github.com/4e6/nixpkgs/compare/release-16.09...4e6:stackage
where I defined `lts-6.25` compiler and was able build our project with it.

The only issue I had with `stackage2nix` is that compiler config should have package names unquoted to be able to override them, see commit [Fix: unquote assignments](https://github.com/NixOS/nixpkgs/commit/7c0ad1dfe594b4a12b6a110a2b79f2631c481ef1)

**Comment by 4e6** [comment]
A small update. I continued @bennofs work on [stackage2nix](https://github.com/4e6/cabal2nix/tree/feature-stackage2nix-up) and made a [stack2nix](https://github.com/4e6/stack2nix) tool on top of it. It takes stack.yaml and creates a Nix derivation with all Stackage packages plus overrides from stack file. 
Also, there is a [stack2nix-examples](https://github.com/4e6/stack2nix-examples) repo that configured to build several public projects with stack2nix. I used this repo as a test to verify the correctness of result derivations but then decided to publish it as well, as it is a good source of examples.

**Comment by domenkozar** [comment]
We have also pursuit and made stack2nix at https://github.com/input-output-hk/stack2nix

It takes a bit different approach, only including packages that are part of `stack list-dependencies`.

**Comment by domenkozar** [comment]
There are two packages, each taking a different approach now, but implementing a basic stack2nix:

- https://github.com/typeable/stackage2nix
- https://github.com/input-output-hk/stack2nix

@peti perhaps we can close this issue as "out of scope" for cabal2nix?

**Comment by peti** [comment]
OK.
