### ISSUE TITLE
No dep to pkgconfig added when .cabal contains pkgconfig-depends

### ISSUE THREAD

**Issue by YPares** [NixOS/cabal2nix#213]
If you run cabal2nix on a .cabal that contains a `pkgconfig-depends:` field, it adds 

`libraryPkgconfigDepends = [...]`

to the .nix file, but shouldn't it also add something like:

`libraryToolDepends = [ pkgconfig ]`

and of course add pkgconfig to the arguments? Or else during the configure phase it just says `No pkg-config found`.

**Comment by peti** [comment]
The generic Haskell builder adds `pkgconfig` to the build inputs automatically when any of the `xxxPkgconfigDepends` attributes is non-empty: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix#L116.

**Comment by YPares** [comment]
@peti Well, as I said, there may be a problem with it as I get `No pkg-config found` when creating a default.nix for the master of http://hackage.haskell.org/package/inline-r, I got the `No pkg-config found` at configure time.

**Comment by peti** [comment]
If you tell me exactly what you are doing, i.e. which commands do you run and what is their output, then I might be able to help. As it is, I have no idea what you're doing. I tried building inline-r from Git, and it worked fine for me.
