### ISSUE TITLE
cabal-install not included in cabal2nix --shell 

### ISSUE THREAD

**Issue by bburdette** [NixOS/cabal2nix#214]
I'm using cabal2nix 20150922 on the unstable nixos channel.  I want to set up an environment in which I can play with this project from lambdaconf 2015:  https://github.com/goldfirere/glambda.

In the nixos user's guide, section 11.3.1 describes using cabal2nix in the following way:
```
$ cabal2nix --shell . >shell.nix
$ nix-shell --command "cabal configure"
```
For me the shell.nix is generated ok.  But for the second step the result is this:
```
[bburdette@nixosthe1:~/code/glambda]$ nix-shell --command "cabal configure"
The program ‘cabal’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.cabal-install
```
I can fix it by adding cabal-install to the the shell.nix like so:
```
[bburdette@nixosthe1:~/code/glambda]$ diff shell.nix shell.nix.meh
9c9
<       , template-haskell, transformers
---
>       , template-haskell, transformers, cabal-install
21c21
<         executableHaskellDepends = [ base ];
---
>         executableHaskellDepends = [ base cabal-install ];
```

But to me this is something that cabal2nix should do for me, if its supposed to be setting up an environment for hacking around with cabal.  Or, the directions on the wiki should change to indicate that you need to add the cabal-install dependency manually.

**Comment by peti** [comment]
Haskell packages can be built in many different ways (like `runhaskell Setup.hs configure && runhaskell Setup.hs build`, `stack build`, etc.) and it feels inappropriate to force a dependency on `cabal-install` onto all our users regardless of whether they actually use that tool or not, hence I believe it's a bad idea to include `cabal-install` in every generated expression. If you want that tool available in your `nix-shell` environments, then it's typically easiest to install it into your user's profile by running `nix-env -i cabal-install`.

**Comment by bburdette** [comment]
If you feel like cabal isn't necessary for the --shell output, ok.  Just pointing out that the docs indicate that cabal will be available, but it is not.  

Maybe the documentation should be changed to indicate that cabal will not be available and you have to install it yourself, since they currently indicate that this should work:
```
$ cabal2nix --shell . >shell.nix
$ nix-shell --command "cabal configure"
```

**Comment by peti** [comment]
Yes, it would be better to explain that situation explicitly in the docs, I agree.

**Comment by stepcut** [comment]
I'd also like `cabal-install` in my environment by default.  I do also agree that it shouldn't be forced upon everyone though.

I also sometimes want to set a different default compiler.  I can *almost* get there by using `cabal2nix` to generate a `shell-gen.nix` and then have a `shell.nix` that overrides the values:

```
let nixpkgs = (import <nixpkgs> {});
in (nixpkgs.haskell.lib.overrideCabal
       (import ./shell-gen.nix { nixpkgs = nixpkgs; compiler = "ghcjs84"; })
     (drv: { buildDepends = (drv.buildDepends or []) ++ 
                [ nixpkgs.haskell.packages.ghc843.cabal-install ]; })).env
```

Unfortunately, this does not work out of the box. The final line of the generate .nix file looks like:

```
if pkgs.lib.inNixShell then drv.env else drv
```

When `nix-shell` is used to evalute the file we get back `drv.env` not `drv`. So for this trick to work I still have to edit the generated file.

I would suggest that perhaps there should be one additional optional argument that allows you to provide an override function in `shell.nix`:

     nixpkgs ? import <nixpkgs> {}, compiler ? "default", doBenchmark ? false; override ? (drv: {}) }:

And then `overrideCabal` would be called automatically. Then I could still use `cabal2nix` to regenerate the dependencies automatically, but also have my custom overrides preserved.

This would allow for many other types of tweaks to the derivation -- not just the addition of cabal-install.

**Comment by stepcut** [comment]
Turns out that maybe I just want to use `developPackage` and create a `shell.nix` like this:

```
with (import <nixpkgs> {}); (haskell.packages.ghcjs84.developPackage
  { root = ./.;
   modifier = (drv: haskell.lib.overrideCabal drv (orig: { executableHaskellDepends = orig.executableHaskellDepends ++ [ haskell.packages.ghc843.cabal-install ]; }));
  })
```
