### ISSUE TITLE
crossSystem assertion fails on nix-shell

### ISSUE THREAD

**Issue by splintrx** [NixOS/cabal2nix#215]
Hi 

I run into an assertion problem after running cabal2nix.

    # cabal2nix --shell . > shell.nix

When I run nix-shell I get: 

    # nix-shell "<nixpkgs>"
    error: assertion failed at /nix/store/6fl9zl5kndczmcsn1m4xfg91zbhpihgf-nixos-14.12.885.b373bf9/nixos/nixpkgs/pkgs/top-level/all-packages.nix:4388:15

Here is what is at that line in my case (starts at 4388):

    binutilsCross = assert crossSystem != null; lowPrio (forceNativeDrv (
      if crossSystem.libc == "libSystem" then darwin.cctools_cross
      else binutils.override {
        noSysDirs = true;
        cross = crossSystem;
      }));

I've tried some alternatives (e.g. nix-shell /src/nixpkgs which points to 421989f obnam: 1.18.2 -> 1.19) but kept running into this crossSystem problem.

I've used cabal2nix before and it was working fine. 
Is this an issue in cabal2nix or is this problem elsewhere? Any pointers? 

FYI:

    cabal2nix-20151217

Thanks!

**Comment by peti** [comment]
You're using `nix-shell` incorrectly, I'm afraid. You probably mean to run `nix-shell shell.nix` or just `nix-shell`.

You'll find more details at http://nixos.org/nixpkgs/manual/#how-to-create-ad-hoc-environments-for-nix-shell and in the `nix-shell` man page.

**Comment by splintrx** [comment]
Thanks for the quick note. I usually just use ```nix-shell shell.nix``` (if it's a manually written shell.nix or generated by some other tool) however in this case I got

    # cabal2nix --shell . > shell.nix
    # nix-shell shell.nix
    error: ‘f’ at /src/hakyll_sandbox/my-site/shell.nix:7:7 called without required argument ‘mkDerivation’, at /nix/store/6fl9zl5kndczmcsn1m4xfg91zbhpihgf-nixos-14.12.885.b373bf9/nixos/nixpkgs/lib/customisation.nix:58:12

That's why I figured I had to pass ```"<nixpkgs>"``` (or /src/nixpkgs) to my nix-shell command... but there I ran into the crossSystem issue.

**Comment by peti** [comment]
That error looks like the shell.nix file generated by cabal2nix might be too new for your Nix setup, i.e. apparently your systems lacks `haskellPackages.mkDerivation`. I'm not sure how that might be possbible. Which version (channel) of NixOS / Nixpkgs do you use by default?

**Comment by splintrx** [comment]
Thanks for the hint.

Currently I am using the nixpkgs-unstable channel with nixos-14.12 maybe that's causing the inconsistency?

    # nix-channel --list
    nixpkgs https://nixos.org/channels/nixpkgs-unstable
    nixos https://nixos.org/channels/nixos-14.12

    # nix-channel --version
    nix-channel (Nix) 1.10

    # nixos-version
    14.12.885.b373bf9 (Caterpillar)

    # nix-env --version
    nix-env (Nix) 1.10

Note: I've also been toying around with a local nixpkgs checkout but as far as I could see the end result is the same.

**Comment by splintrx** [comment]
*Update*: I upgraded to the nixos-15.09 channel, switched to ```15.09.947.6783594 (Dingo)``` and now it works, thanks!
