### ISSUE TITLE
Don't skip custom-setup section

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/cabal2nix#216]
Currently the custom-setup section is just skipped. It'd be great if it could be accounted for.

This stanza is new in cabal 1.23 and details dependencies for the Setup.hs script. This section is required if the build type is Custom.

This issue is similar to #90

**Comment by mdorman** [comment]
And this just became more important, as all the things that used to depend on gtk2hs-buildtools are now embedding calls to it as a library in their custom setups, and trying to include it via this mechanism, and failing.

**Comment by peti** [comment]
Implemented in 90ca02318304e67d01b8e6cb0c779aaf342e66d6.
