### ISSUE TITLE
Pass cabal file itself instead of directory.

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/cabal2nix#220]
I like to run cabal2nix with an import from derivation:
```nix
 dynamicCabal2nix = dir: pkgs.runCommand "dynamic-cabal2nix" {
     nativeBuildInputs = [ pkgs.haskellPackages.cabal2nix ];
   } "cabal2nix ${dir} > $out";
```
To avoid copying tons of stuff to the store just to get in a development shell, I'd like to invoke that as `dynamicCabal2nix ./my-pkg.cabal`. But cabal2nix only accepts directories, not cabal files directly. My current work around is an additional `runCommand` to copy the cabal file to a new empty directory---not very elegant.

**Comment by peti** [comment]
> cabal2nix only excepts directories, not cabal files directly.

Huh? What makes you say that?

**Comment by Ericson2314** [comment]
`s/excepts/accepts/`, oops.

```shell
$ cabal2nix ./redoak.cabal 
downloading ‘http://hackage.haskell.org/package/redoak-0.1.0.0.tar.gz’... [0/0 KiB, 0.0 KiB/s]
error: unable to download ‘http://hackage.haskell.org/package/redoak-0.1.0.0.tar.gz’: HTTP response code said error (22)
*** cannot compute hash. (Not a hackage project?)
 If your project is not on hackage, please supply the path to the root directory of
 the project, not to the cabal file.

 If your project is on hackage but you still want to specify the hash manually, you
 can use the --sha256 option.
```

**Comment by peti** [comment]
Please specify `--sha256=somevalue` to fix that error.

**Comment by Ericson2314** [comment]
Huh? but my project is *not* on hackage. I'm asking if `cabal2nix ./foobar.cabal` to do the same thing as `cabal2nix ./.`.

**Comment by Ericson2314** [comment]
> If your project is not on hackage, please supply the path to the root directory of
 the project, not to the cabal file.

Sounds like you intentionally ruled out this functionality. In which I am curious why.

**Comment by peti** [comment]
The syntax `cabal2nix foo.cabal` has always been used to generate build instructions for a Hackage package, and I don't think it's a good idea to change that behavior now after having established that for 4+ years or so.

If you'd like to cut down on the amount of files copied into the store to generate the expression, then `builtins.filterSource` might be the solution you're looking for.

**Comment by Ericson2314** [comment]
> If the URI refers to a cabal file, information for building the package will
  be retrieved from that file, but hackage will be used as a source for the
  derivation. Otherwise, the supplied URI will be used to as the souce for the
  derivation and the information is taken from the cabal file at the root of the
  downloaded source.

Ok, now I understand the rational for the current way things are done better. Maybe the solution is then to add a `--source=<nix expression>`, `--source=<path>`, or `--null-source` flag? I currently set the `src` with `overrideCabal` for nix-shell, and keep it as is for full builds, in order to copy the minimal amount of stuff. With this flag, I'd just do that in reverse.

**Comment by peti** [comment]
Yes, a well thought-out scheme for specifying various kinds of sources via command line flags would be really great. The current approach is a bit of a mess.

**Comment by Ericson2314** [comment]
Yeah on one hand I wanted to do something powerful like `--source=<nix expression>`, on the other hand since my usecase is generating the expression dynamically anyways, the `overrideCabal`ing whatever I actually want there isn't really a burden. The main thing is just to prevent the (slow and potentially doomed to fail) hackage query.

**Comment by Ericson2314** [comment]
Should I rename this one / open a new issue about specifying a custom or null src attribute?

**Comment by peti** [comment]
Personally, I don't think it's helpful to have an open issue that's so generic and has such a broad scope like "re-design CLI", so I'm not keen on it.

**Comment by Ericson2314** [comment]
Hmm? I mean an issue specifically for one of `--source=<nix expression>`,` --source=<path>`, or `--null-source`.

**Comment by peti** [comment]
As I said, the underlying issue is that we need to design a CLI that is sufficiently powerful for people to specify all kinds of different choices. This is really a *design issue*. Once someone comes up with a proper CLI, it's straight-forward to implement that in Haskell, but we don't have any proposal to that end yet.

Personally, my interest is in getting the CLI right, at last, so I'm reluctant to add any new features in the meanwhile that don't necessarily fit into the big picture in the end.

**Comment by Ericson2314** [comment]
Are you interested in overhauling the CLI then? https://github.com/NixOS/cabal2nix/issues/220#issuecomment-193970692 led me to think the opposite.
