### ISSUE TITLE
vector-algorithms missing executableHaskellDepends

### ISSUE THREAD

**Issue by puffnfresh** [NixOS/cabal2nix#238]
Using cabal2nix 20160308 I get a working build of vector-algorithms:

```nix
{ mkDerivation, base, bytestring, containers, mtl, mwc-random
, primitive, QuickCheck, stdenv, vector
}:
mkDerivation {
  pname = "vector-algorithms";
  version = "0.7.0.1";
  sha256 = "0w4hf598lpxfg58rnimcqxrbnpqq2jmpjx82qa5md3q6r90hlipd";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [ base bytestring primitive vector ];
  executableHaskellDepends = [ base mtl mwc-random vector ];
  testHaskellDepends = [
    base bytestring containers QuickCheck vector
  ];
  homepage = "http://code.haskell.org/~dolio/";
  description = "Efficient algorithms for vector arrays";
  license = stdenv.lib.licenses.bsd3;
}
```

Using cabal2nix 2.0 I get a version which fails exactly like https://github.com/NixOS/nixpkgs/issues/16343:

```nix
{ mkDerivation, base, bytestring, containers, primitive, QuickCheck
, stdenv, vector
}:
mkDerivation {
  pname = "vector-algorithms";
  version = "0.7.0.1";
  sha256 = "0w4hf598lpxfg58rnimcqxrbnpqq2jmpjx82qa5md3q6r90hlipd";
  libraryHaskellDepends = [ base bytestring primitive vector ];
  testHaskellDepends = [
    base bytestring containers QuickCheck vector
  ];
  homepage = "http://code.haskell.org/~dolio/";
  description = "Efficient algorithms for vector arrays";
  license = stdenv.lib.licenses.bsd3;
}
```

Notice that the `executableHaskellDepends` field isn't being generated. I guess this is because `bench` being false triggers the executable to not build, but it seems Cabal still checks if the dependencies exist.

**Comment by peti** [comment]
`cabal2nix` generates build expressions that target ghc 8.x by default, and the new compiler does not need those additional dependencies. Unfortunately, this means that those dependencies are missing when building with ghc 7.x or older, but there is no easy fix for this issue (except manually adding overrides for the  older compilers).
