### ISSUE TITLE
installing hakyll fails on OSX due to linux requirement `utillinux`

### ISSUE THREAD

**Issue by mjhoy** [NixOS/cabal2nix#239]
I believe this was introduced in cb85ef4

I'm not very familiar with nix, but shouldn't there be a generic way to provide `rev`?

**Comment by domenkozar** [comment]
@peti can we condition that dependency based on `isDarwin`?

**Comment by peti** [comment]
We can override `hakyll = super.hakyll.override { utillinux = null; }` on Darwin via `common-overrides.nix`.

**Comment by domenkozar** [comment]
This was actually fixed in https://github.com/NixOS/nixpkgs/issues/19294#issuecomment-270407498
