### ISSUE TITLE
nixpkgs systemd has been changed to systemd.lib

### ISSUE THREAD

**Issue by rickynils** [NixOS/cabal2nix#244]
In https://github.com/NixOS/nixpkgs/commit/78178d5854901e1b17a14bce3fe43515984b7b91, the systemd libs was moved to `systemd.lib`. This breaks Haskell packages that depends on the system package `libsystemd` (for example `libsystemd-journal`).

The diff below is likely what is needed in cabal2nix (although I'm unsure if we support returning expressions like `systemd.lib` expressions here), but I haven't been able to verify it since I haven't found a fresh nixpkgs revision that works for building cabal2nix (I get various Haskell version conflicts for cabal-install etc).

```
diff --git a/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs b/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs
index c86bd1f..9f362fe 100644
--- a/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs
+++ b/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs
@@ -105,7 +105,7 @@ libNixName "libR"                               = return "R"
 libNixName "librsvg-2.0"                        = return "librsvg"
 libNixName "libsoup-2.4"                        = return "libsoup"
 libNixName "libsoup-gnome-2.4"                  = return "libsoup"
-libNixName "libsystemd"                         = return "systemd"
+libNixName "libsystemd"                         = return "systemd.lib"
 libNixName "libusb-1.0"                         = return "libusb"
 libNixName "libxml-2.0"                         = return "libxml2"
 libNixName "libzip"                             = return "libzip"
@@ -151,10 +151,10 @@ libNixName "sqlite3"                            = return "sqlite"
 libNixName "ssl"                                = return "openssl"
 libNixName "stdc++"                             = [] -- What is that?
 libNixName "stdc++.dll"                         = [] -- What is that?
-libNixName "systemd-journal"                    = return "systemd"
+libNixName "systemd-journal"                    = return "systemd.lib"
 libNixName "taglib_c"                           = return "taglib"
 libNixName "tag_c"                              = return "taglib"
-libNixName "udev"                               = return "systemd";
+libNixName "udev"                               = return "systemd.lib";
 libNixName "uuid"                               = return "libossp_uuid";
 libNixName "vte-2.90"                           = return "vte"
 libNixName "vte-2.91"                           = return "vte"
```

**Comment by peti** [comment]
>  I haven't been able to verify it since I haven't found a fresh nixpkgs revision that works for building cabal2nix.

You should be able to compile `cabal2nix` in recent versions of Nixpkgs simply by running:

    $ nix-shell "<nixpkgs>" -A haskellPackages.cabal2nix.env --run "cabal configure"

and then "cabal build", etc. Iif that doesn't work, then you probably have global state in `~/.ghc` or `~/.cabal`.

**Comment by peti** [comment]
One problem I see is that using the `lib` output is probably not going to work either because that path does not include the header files, so the argument passed to `--extra-include-dir` during the configure stage will be wrong and/or useless.

The best solution IMHO is to have the generic Haskell builder apply `getDevDir` and `getLibDir` to the system dependency paths, respectively, to make sure the proper output is chosen for each context.

**Comment by peti** [comment]
This issue has been fixed a while ago.
