### ISSUE TITLE
cabal2nix skips ghcjs-base as a dependency from react-flux

### ISSUE THREAD

**Issue by themoritz** [NixOS/cabal2nix#248]
Running `$ cabal2nix cabal://react-flux` somehow skips `ghcjs-base` as a dependency. This makes it fail to compile under ghcjs: https://github.com/NixOS/nixpkgs/issues/16583.

Possible cause could be the way the dependency is declared in the `.cabal` file of react-flux:

```
  if impl(ghcjs)
      build-depends: ghcjs-base
```

**Comment by peti** [comment]
Please run the converter as follows: `cabal2nix --compiler=ghcjs cabal://react-flu`.
