### ISSUE TITLE
Support hpack

### ISSUE THREAD

**Issue by 3noch** [NixOS/cabal2nix#249]
If cabal2nix notices a `package.yaml` file, it could generate the `cabal` file first, right?

**Comment by razvan-panda** [comment]
Any update on this? How hard would it be to implement? If no one offers I will do it.

**Comment by 3noch** [comment]
@razvan-panda No it's actually quite easy:

```nix
let

  hpack2cabal = name: src: pkgs.runCommand "hpack2cabal-${name}" {} ''
    ${pkgs.haskellPackages.hpack}/bin/hpack '${src}' - > "$out"
  '';

in haskellPackages.override {
  overrides = self: super: {
    callHpack2nix = name: src: self.callCabal2nix name (hpack2cabal name src);
  }
}
```

It would be easy to add variants that check for a `package.yaml` file first. Checking for a `cabal` file would not be good because many Hpack repos keep their cabal files around. I'm torn as to whether it is a good idea to do this by default in `callCabal2nix`, but certainly a `callHpack2nix` would be fine.

**Comment by 3noch** [comment]
I think best of all would be to add this directly to `cabal2nix` and get the behavior for everything out of the box.

**Comment by razvan-panda** [comment]
@3noch Since you already did it - would you like to do a pull request? 👍

**Comment by 3noch** [comment]
@razvan-panda Sure. Haha...I've been meaning to. Thanks for the nudge.

**Comment by razvan-panda** [comment]
@3noch Cheers! You are doing science's work! 👍

**Comment by tomsmalley** [comment]
I have just implemented this in PR #304 so that hpack is used as a fallback (or can be forced by a command line flag).

**Comment by tomsmalley** [comment]
@3noch the PR has now been merged!

**Comment by ip1981** [comment]
@3noch did you mean
```
callCabal2nix = name: src: self.callCabal2nix name (hpack2cabal name src);
```
?

**Comment by 3noch** [comment]
No, I wasn't implementing it recursively. Does thta work?

**Comment by ip1981** [comment]
I don't know :)

**Comment by ip1981** [comment]
Guys, I'm trying to apply new cabal2nix to a package without `.cabal` file, and encountered another issue.

**2.4:** fetches sources, but can't find a `.cabal` file, ok.
```
# cabal2nix --version
cabal2nix 2.4.1

# cabal2nix https://github.com/commercialhaskell/stack >/dev/null
downloading ‘https://github.com/commercialhaskell/stack’... [0/0 KiB, 0.0 KiB/s]
*** parsing cabal file: https://github.com/commercialhaskell/stack: openBinaryFile: does not exist (No such file or directory)
Initialized empty Git repository in /tmp/git-checkout-tmp-b4dB4diF/stack/.git/
remote: Counting objects: 677, done.
remote: Compressing objects: 100% (505/505), done.
remote: Total 677 (delta 60), reused 525 (delta 30), pack-reused 0
Receiving objects: 100% (677/677), 698.63 KiB | 1.38 MiB/s, done.
Resolving deltas: 100% (60/60), done.
From https://github.com/commercialhaskell/stack
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...

git revision is c447ed63b9279d0c7659ac18c63553b9abd36193
path is /nix/store/l9yxx35slzg9js6sm7294mx0wk3f6w80-stack
git human-readable version is -- none --
Commit date is 2017-12-06 21:38:24 -0800
hash is 1gp5w030wi3fsyly33v3kq1zq3akp7ac31rad6g64n5shq5d8j02
*** found zero or more than one cabal file ([]). Exiting.
```

**2.7:** fails to fetch sources, so I can't test new `hpack` feature :)
```
# ~/.cabal/bin/cabal2nix --version
cabal2nix 2.7

# ~/.cabal/bin/cabal2nix https://github.com/commercialhaskell/stack >/dev/null
downloading ‘https://github.com/commercialhaskell/stack’... [0/0 KiB, 0.0 KiB/s]
*** parsing cabal file: https://github.com/commercialhaskell/stack: openFile: does not exist (No such file or directory)
cabal2nix: nix-prefetch-git: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by ip1981** [comment]
Nevermind, sorry for the noise :)
