### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by Fresheyeball** [NixOS/cabal2nix#253]
http://hydra.nixos.org/job/nixpkgs/trunk/manual/latest/download-by-type/doc/manual#users-guide-to-the-haskell-infrastructure

![image](https://cloud.githubusercontent.com/assets/609279/20695564/3e5e287a-b5aa-11e6-9c28-656c0e7f5215.png)

**Comment by peti** [comment]
Thanks  for the heads-up!
