### ISSUE TITLE
cabal2nix misses dependencies when generating expression for semigroups package

### ISSUE THREAD

**Issue by grwlf** [NixOS/cabal2nix#257]
I've tried to build `semigroups-0.18.2` expression with the following command:

```
  $ cabal2nix --no-check --no-haddock

```
As a result, cabal2nix builds the expression listed below:
```
{ mkDerivation, base, stdenv }:
mkDerivation {
  pname = "semigroups";
  version = "0.18.2";
  src = ./semigroups-0.18.2;
  libraryHaskellDepends = [ base ];
  doHaddock = false;
  doCheck = false;
  homepage = "http://github.com/ekmett/semigroups/";
  description = "Anything that associates";
  license = stdenv.lib.licenses.bsd3;
}
```

In the same time, the .cabal of this package describes many compile flags. By default, it should also depend on `hashable, tagged, text, unordered-containers`. I'm using cabal2nix 2.0.1.

**Comment by peti** [comment]
None of these dependencies exist in `semigroups` for GHC 8.x or later; these are defined only for GHC < 7.11.20151002. If you want to build the package with an older compiler, you'll have to provide an appropriate `--compiler=...` flag to `cabal2nix`.
