### ISSUE TITLE
cabal2nix misses dependencies when generating expression for attoparsec package

### ISSUE THREAD

**Issue by grwlf** [NixOS/cabal2nix#258]
While building the exression for `attoparsec-0.13.1.0` package, cabal2nix misses dependencies. Probably this is due to `if` condition used in .cabal file:
```
  if !impl(ghc >= 8.0)
    -- Data.Semigroup && Control.Monad.Fail are available in base-4.9+
    build-depends: fail == 4.9.*, semigroups >=0.16.1 && <0.19
```

I'm using ghc-7.10.3 so I'm expecting the `fail` and `semigroups` dependencies to be included. In reality, none of this was listed in the expression. I'm using cabal2nix 2.0.1.

**Comment by peti** [comment]
Please run `cabal2nix` with the parameter `--compiler=ghc-7.10`.

**Comment by grwlf** [comment]
Thanks, with `--compiler=ghc-7.10` it works as expected.
