### ISSUE TITLE
Move away from nix-prefetch-zip

### ISSUE THREAD

**Issue by mckeankylej** [NixOS/cabal2nix#263]
When I install `cabal2nix` with the latest unstable I get the following error:
```bash
bash-3.2$ cabal2nix https://github.com/mckeankylej/chronos.git > chronos.nix
cabal2nix: nix-prefetch-zip: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
See https://github.com/NixOS/nixpkgs/issues/23230

**Comment by peti** [comment]
The update to cabal2nix 2.1 will fix this in `master` a couple of hours.

**Comment by 3noch** [comment]
I'm still seeing this in latest nixpkgs-unstable.

**Comment by 3noch** [comment]
Never mind; I have to look more closely to find the issue.
