### ISSUE TITLE
Name collision; `error: infinite recursion encountered, at undefined position`

### ISSUE THREAD

**Issue by jmitchell** [NixOS/cabal2nix#273]
# Unexpected behavior

Haskell packages sometimes have the same name as one of their dependencies (e.g. common with C library wrappers), but `cabal2nix` currently mixes the namespaces and causes name collisions.

# Example

There's already a maintained nix-expression for the `ncurses` package, but it serves as a good example:

```
$ cabal2nix https://john-millikin.com/code/haskell-ncurses/ > ncurses.nix
$ cat << EOF > default.nix
{ pkgs ? (import <nixpkgs> {})
, compiler ? pkgs.haskell.packages.ghc802
}:

with (import <nixpkgs/pkgs/development/haskell-modules/lib.nix> { inherit pkgs; });

compiler.override {
  overrides = self: super: {
    ncurses = super.callPackage ./ncurses.nix { };
  };
}
EOF
$ nix-build -A ncurses --show-trace
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘ncurses-0.2.16’ at /nix/store/2hja4vgpiqcy4i7w7s96ciiyx562mxf1-nixos-17.03.945.5acb454e2a/nixos/pkgs/development/haskell-modules/generic-builder.nix:171:3:
infinite recursion encountered, at undefined position
```

# Manual Fix

1. Rather than depend on `ncurses` directly, pass `pkgs`.
2. Use `pkgs.ncurses` instead of `ncurses` in the generated `librarySystemDepends` list.

**Comment by peti** [comment]
`cabal2nix` generates a function that takes the dependencies as arguments. If the default name resolution doesn't work out, then the proper way to remedy that issue is to pass the correct argument when you call the generated expression, i.e.: 

~~~
  overrides = self: super: {
    ncurses = self.callPackage ./ncurses.nix { inherit (pkgs) ncurses; };
  };
~~~

**Comment by jmitchell** [comment]
@peti, thanks for the helpful and quick reply. I believe this will work nicely with my use case.
