### ISSUE TITLE
Adding dependencies from subprojects

### ISSUE THREAD

**Issue by pjones** [NixOS/cabal2nix#277]
Both cabal and stack support the idea of subprojects.  For recent versions of cabal you can set the `packages` key in the `cabal.project` file, an improvement to the `add-source` sandbox command.

Are there any plans (or objections) to reading multiple cabal files and generating a derivation that merges all of the dependencies?

**Comment by domenkozar** [comment]
Related to https://github.com/NixOS/cabal2nix/issues/261

**Comment by peti** [comment]
I believe it's better to create Nix expressions for ever sub-project individually and then merge them into a  super-environment on the Nix-level, rather than having cabal2nix do that.

**Comment by pjones** [comment]
That sounds fair.  I'll do that.   Thanks.
