### ISSUE TITLE
cabal2nix started to ignore package version

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/cabal2nix#287]
On nixpkgs 53931c0443f1a4402f4b690459b9a5d4919fb431

run `cabal update` then

```
[nix-shell:/tmp/tmphome/cabal-db-master]$ cabal2nix cabal://sqlite-simple-0.4.13.0
downloading ‘http://hackage.haskell.org/package/sqlite-simple-0.4.14.0.tar.gz’... [0/0 KiB, 0.0 KiB/s]
{ mkDerivation, attoparsec, base, base16-bytestring, blaze-builder
, blaze-textual, bytestring, containers, direct-sqlite, HUnit, Only
, stdenv, text, time, transformers
}:
mkDerivation {
  pname = "sqlite-simple";
  version = "0.4.14.0";
  sha256 = "0zx4fdv6larfyj6m1d4livb5cqdx10yi06yd6px2n0wnxcmvdyj9";
  libraryHaskellDepends = [
    attoparsec base blaze-builder blaze-textual bytestring containers
    direct-sqlite Only text time transformers
  ];
  testHaskellDepends = [
    base base16-bytestring bytestring direct-sqlite HUnit text time
  ];
  homepage = "http://github.com/nurpax/sqlite-simple";
  description = "Mid-Level SQLite client library";
  license = stdenv.lib.licenses.bsd3;
}
```

This is a regression: we are pinning a Hackage DB in our project and 0.4.13.0 was picked previously while modern cabal2nix picks 0.4.14.0 (latest) from the very same DB.

**Comment by Fuuzetsu** [comment]
Problem at `lookupVersion` function which just picks newest version from DB regardless of what the user typed in. Cooking a fix…

**Comment by peti** [comment]
Hm, this may have happened when I ported the tool to Cabal 2.x.

**Comment by domenkozar** [comment]
Could we release this? It currently breaks many things as latest cabal2nix release out there is not working :)

**Comment by peti** [comment]
Yeah, good point: http://hackage.haskell.org/package/cabal2nix-2.4.1
