### ISSUE TITLE
Which hackage repo should be used?

### ISSUE THREAD

**Issue by cocreature** [NixOS/cabal2nix#291]
I’m trying to figure out how to run `hackage2nix`. It references a `preferred-versions` file in a `hackage` folder which I thought was the `hackage` branch of https://github.com/commercialhaskell/all-cabal-hashes but that repository no longer has that file (see https://github.com/commercialhaskell/all-cabal-files/issues/8). Is there some other repo that has this file? If not what’s the proper process for running `hackage2nix`?

**Comment by peti** [comment]
Please check out https://github.com/NixOS/cabal2nix/blob/master/update-nixpkgs.sh#L23-L31, which generates the required file.
