### ISSUE TITLE
Help to add generated package to nixpkgs 

### ISSUE THREAD

**Issue by teto** [NixOS/cabal2nix#292]
hi,
I successfully used cabal2nix and managed to install locally greenclip. 
`https://github.com/erebe/greenclip/issues/12`
I would like to upstream it to nixpkgs but I find the manual lacking on this subject (and I am not very familiar with nix too). I've been looking for similar haskell default.nix but most packages seem to be from hackage. 

Thus I've added this file pkgs/misc/greenclip/default.nix (modified version of the cabal2nix) :
```
# { haskellPackages ? (import <nixpkgs> {}).haskellPackages,
# stdenv ? (import <nixpkgs> {}).stdenv }:
# todo look at generic-builder
{ mkDerivation, base, binary, classy-prelude, Clipboard, directory
, microlens, microlens-mtl, stdenv, text, vector, fetchFromGitHub
}:
let
  # super.haskellPackages.C
   clipboard = Clipboard.overrideAttrs (oldAttrs: {
	  name = "Clipboard";
	  src = ./lib/Clipboard;
	});
in
 mkDerivation rec {
  pname = "greenclip";
  version = "2.0";
  src = fetchFromGitHub {
    owner = "erebe";
    repo = "greenclip";
    rev = "${version}";
    sha256 = "1326nh2jiirn1xrpnd5kc71vy0r1mr6cv6yh1sgg3rwd51s5zbpa";
  };
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base binary classy-prelude clipboard directory microlens
    microlens-mtl text vector
  ];
  # buildDepends= [ Clipboard ];
  meta = {
  homepage = "https://github.com/erebe/greenclip#readme";
  description = "Simple clipboard manager to be integrated with rofi";
  license = stdenv.lib.licenses.bsd3;
  # maintainers =
  };
}
```
The "mkDerivation" seem to be defined in generated-builder.nix but I wonder if cabal2nix is the correct way to upstream a package ? This might not be the best place to ask but I hope you can provide me with a link/an example I can mimic.

**Comment by peti** [comment]
Why don't you just upload this package to Hackage? Then it will be picked up automatically.

**Comment by teto** [comment]
I am not the owner of the project (I could ask the owner though). Greenclip embeds a fork of the Clipboard library so I am not sure hackage would work out of the box either ?

**Comment by peti** [comment]
I see. Well, having it (and its dependencies) on Hackage is definitely the preferred solution. If that doesn't work, then you can use the tool `tinc` as an example how to add a non-Hackage package to Nixpkgs. The relevant files are in `pkgs/development/tools/haskell/tinc` and `pkgs/development/haskell-modules/configuration-common.nix`.

**Comment by teto** [comment]
thanks for the help. I will definitely give it a try. I close the issue since it was a bit out of scope in the first place.
