### ISSUE TITLE
cabal2nix 2.4.1 fails to use the hackage db

### ISSUE THREAD

**Issue by domenkozar** [NixOS/cabal2nix#298]
To reproduce:

```
$ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/824b8e4c6a2ac49dc9867dc9105372b15d5378f6.tar.gz nix-shell -p cabal2nix cabal-install --run "rm -rf ~/.cabal && cabal update && cabal2nix cabal://mtl"
...
cabal2nix: /home/ielectric/.cabal/packages/hackage.haskell.org/00-index.tar: openBinaryFile: does not exist (No such file or directory)
```

It seems that Cabal 2.0 uses `01-index.tar.gz` so passing `--hackage-db ~/.cabal/packages/hackage.haskell.org/01-index.tar` works.

**Comment by domenkozar** [comment]
Related to #297

**Comment by domenkozar** [comment]
Yeah it's related, https://github.com/peti/hackage-db is out of date with Cabal 2.0

**Comment by dcoutts** [comment]
Looks like the current git version does have support for the new index format, including snapshot ability.

**Comment by peti** [comment]
Yes, hackage-db 2.x has full support for the index-01 tarball. I haven't released it yet because I'd like to port `cabal2nix` and `cabal2obs` to the new version first to make sure the API is reasonable. It shouldn't take long to accomplish that, though.

**Comment by domenkozar** [comment]
@peti could I help you with something here? It's blocking us from using multiple outputs work
