### ISSUE TITLE
Versions missing in new package index

### ISSUE THREAD

**Issue by domenkozar** [NixOS/cabal2nix#306]
```
$ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/042ca21c812ae3c3fd52f3fdec41699b193dcfbf.tar.gz nix-shell -p cabal2nix --run "cabal2nix cabal://fgl-5.5.4.0"
downloading ‘https://github.com/NixOS/nixpkgs/archive/042ca21c812ae3c3fd52f3fdec41699b193dcfbf.tar.gz’... [0/0 KiB, 0.0 KiB/s]
cabal2nix: user error (No such package in the cabal database. Did you run cabal update?)
```

If I unpack `~/.cabal/packages/hackage.haskell.org/01-index.tar.gz` I see:

```
$ ls fgl/5.5.4.0/
fgl.cabal  package.json
```

Probably related to the new hackage db /cc @peti

**Comment by peti** [comment]
`fgl-5.5.4.0` is deprecated on Hackage: http://hackage.haskell.org/package/fgl/preferred.

**Comment by domenkozar** [comment]
It may be considered as deprecated, but it's part of latest stackage LTS: https://www.stackage.org/lts-9.6/package/fgl-5.5.4.0

Bumping to fgl-5.6.0.0 breaks compilation for graphviz at very least.

So I don't see why cabal2nix should prevent me from using it - I would understand a warning or at very least an opt-in.

**Comment by domenkozar** [comment]
Same for nixpkgs master:

```
$ nix-build -A haskellPackages.fgl
these paths will be fetched (0.55 MiB download, 6.98 MiB unpacked):
  /nix/store/f83wlnzlfqmqvcvxjdqkbn93q6wqbavf-fgl-5.5.4.0-doc
  /nix/store/w72h6zj4q1snpzav5j36xjrnks7diqv6-fgl-5.5.4.0
```

**Comment by peti** [comment]
> It may be considered as deprecated, but it's part of latest stackage LTS.

Yes, this is clearly an error. I reported this at https://github.com/fpco/lts-haskell/issues/70 a while ago, and it would be great if this were resolved. Unfortunately, I can't do much about it, personally. It's up to the Stackage people to fix this.

**Comment by domenkozar** [comment]
We can do, we shouldn't prevent people from using specific versions until stackage has this process figure out for themselves. Otherwise we'll costantly be blocked - I still think we should have an opt-in

**Comment by peti** [comment]
If we ignore the information from *Hackage*, then we effectively deny upstream package authors the ability to deprecate a package that was released accidentally with serious defects. That doesn't seem like a good idea.

**Comment by domenkozar** [comment]
I've never set we should ignore it. I'm saying that currently cabal2nix says that such package does not exist and this has two problems:

1) it's unclear why
2) there's no way to overcome the limitation
