### ISSUE TITLE
Explain how to fix problems in hackage-packages.nix

### ISSUE THREAD

**Issue by ledettwy** [NixOS/cabal2nix#310]
The comments in package-packages.nix only explain that it's an auto-generated file and only tell users to not edit the file, without giving any hints as to how to fix problems with it. I suggest improving the comment documentation in this file especially for problems related to library name mappings from cabal to Nix, since there are likely a lot of holes. See: NixOS/cabal2nix#309

**Comment by peti** [comment]
Please don't hesitate to submit enhancements by way of a pull request.
