### ISSUE TITLE
Internal Libraries in Cabal 2.+

### ISSUE THREAD

**Issue by ts468** [NixOS/cabal2nix#315]
Cabal 2.0 and later support “internal libraries” [1]. Internal libraries are named library sections in a `.cabal`-file that can be referenced in other build-depends like any other, external package, but are resolved internally by cabal.

Cabal2nix seems to generate external dependencies for internal libraries as well. Did somebody already look into extending cabal2nix to filter out internal libraries before generating the external dependencies?

[1] https://www.haskell.org/cabal/users-guide/developing-packages.html#library

**Comment by tomsmalley** [comment]
See PR #316

**Comment by ts468** [comment]
@tomsmalley @peti Thank you so much for your efforts!!!
