### ISSUE TITLE
2.7.1 breaks callCabal2nix

### ISSUE THREAD

**Issue by hamishmack** [NixOS/cabal2nix#319]
I was checking some stuff against `nixpkgs/master` and `callCabal2nix` seems to always fail with

```
cabal2nix: NoHackageTarballFound
```

I am testing on macOS.  It seems to happen for anything using `callCabal2nix`.  Changing the version of `cabal2nix` to 2.7 (and updating the hash) in `hackage-packages.nix` seems to work around the issue.

**Comment by peti** [comment]
My *guess* is that c9948f9f51e313a39cdc3023467f9783275e94a9 might have something to do with this. Ping @jmitchell.

**Comment by domenkozar** [comment]
I'll take a look tomorrow.

**Comment by pikajude** [comment]
thanks!

**Comment by domenkozar** [comment]
Looking.

**Comment by domenkozar** [comment]
I see the problem is really in https://github.com/NixOS/cabal2nix/commit/c9948f9f51e313a39cdc3023467f9783275e94a9, because now it loads `hackageDB` before it decides from where the cabal file will come from.

**Comment by domenkozar** [comment]
I don't yet see how to best solve this, could we make `readTarball` lazy so that hackage-db is parsed only on access? https://github.com/NixOS/cabal2nix/blob/master/src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs#L81

**Comment by domenkozar** [comment]
I have a working solution at https://github.com/NixOS/cabal2nix/pull/321
