### ISSUE TITLE
Fully specified dependencies option.

### ISSUE THREAD

**Issue by seanparsons** [NixOS/cabal2nix#330]
One thing I've wanted is a way of having cabal2nix function somewhat similarly to npm2nix in that it gets Cabal to resolve the dependencies (the particular versions and revisions) then creates a series of interwoven derivations that match up with those. Is there any interest (other than mine) in this being added to cabal2nix?

My motivation is to not have to do this kind of thing:
https://github.com/seanparsons/podcast-chooser/blob/master/podcast-chooser.nix#L8
Ideally I could just regenerate the `podcast-chooser.nix` file with cabal2nix specifying said option and it would mean that I'd get the right dependency of path-io without having to do that little dance.

**Comment by peti** [comment]
I think this is pretty much what `hackage2nix` does.

**Comment by seanparsons** [comment]
@peti From what I understand of hackage2nix I think the answer is sort of. :)

It looks like I would have to manually generate the `configuration-hackage2nix.yaml` run that and that would provide me with the various derivations and then I'd have to hook that up to whatever cabal2nix generated.

I want a single `cabal2nix` invocation to give me the main derivation for the project as well as the dependencies. Also very specifically for those dependencies to use the versions of the libraries that Cabal would use if I just did a straight `cabal build` without nix being involved.

**Comment by seanparsons** [comment]
@peti I've spent a few hours looking at this today and I'm surprised how much of a pain Cabal makes it. The most reasonable API around resolving dependencies is in cabal-install which I find a little baffling.

One solution that I'm currently thinking about for solving my problem is running `cabal freeze --dry-run` on the command line, feeding the output of that to a bunch of `cabal2nix` invocations and then stitching the result together like some kind of awful Frankenstein of an approach.

**Comment by sol** [comment]
@seanparsons we (@robbinch and I) added that to [`sol/tinc`](https://github.com/sol/tinc/commits/master).  It uses `cabal-install` to resolve dependency, then creates nix expressions from that install plan.

Note that you can also use local and git dependencies (either directly in `package.yaml` or as an override in `tinc.yaml`).

It's not widely advertised, but if you are not afraid of some rough edges you may give it a try, and possibly @robbinch can step up and get you started.

**Comment by seanparsons** [comment]
@sol ORLY? Ironically I reached this point because I was looking at styx as I didn't _think_ I'd be able to create a multi-project GHCJS/GHC site (shared core project, etc) with tinc. I think I'll bin this ticket off and have a looky see at tinc.

**Comment by seanparsons** [comment]
I'm tempted to re-open this issue because I want to integrate the nix expressions into a larger project. For example one that is a combination of Haskell and Purescript code. A multi-project setup might even necessitate differing dependencies of the same library for 2 or more different servers.

**Comment by peti** [comment]
Please don't re-open that issue. We already have a tool that generates package sets -- `hackage2nix`. I will not duplicate that functionality in `cabal2nix`.

**Comment by peti** [comment]
Create an appropriate `configuration-hackage2nix.yaml` in a Nixpkgs branch, run `hackage2nix`, and there you go! :-) If you want a more convenient way to run the tool, you might have to hack it a bit, though. It's been designed with Nixpkgs in mind and I reckon your use case is slightly different.

**Comment by seanparsons** [comment]
@peti Yeah, that's not even remotely sensible for this use case, it should be local to the project and not need a special branch of nixpkgs somewhere. Plus for my multiple project use case it would necessitate multiple branches of nixpkgs. I purely want something that uses the versions from `cabal.project.freeze` (ideally also `cabal.project`) to create the derivations for the dependencies.

**Comment by peti** [comment]
Once you generated a new `hackage-packages.nix` file, you can override the default package set in your Nixpkgs version with the generated one. You don't have to use a branch if you don't want to.
