### ISSUE TITLE
hackage2nix: thread blocked indefinitely in an MVar

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/cabal2nix#355]
```
$ hackage2nix --nixpkgs=$PWD/nixpkgs +RTS -M4G -RTS
hackage2nix: Distribution.Nixpkgs.Haskell.FromCabal.License.fromCabalLicense: unknown licenseUnknownLicense "CC0-1.0"
Choose one of: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD2, BSD3, MIT, ISC, MPL-2.0, Apache, Apache-2.0, PublicDomain, AllRightsReserved, OtherLicense
CallStack (from HasCallStack):
  error, called at src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs:38:62 in cabal2nix-2.9.2-3Ov8Inn3Kbg3imbyfO8PUw:Distribution.Nixpkgs.Haskell.FromCabal.License
hackage2nix: Distribution.Nixpkgs.Haskell.FromCabal.License.fromCabalLicense: unknown licenseUnknownLicense "CC0-1.0"
Choose one of: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD2, BSD3, MIT, ISC, MPL-2.0, Apache, Apache-2.0, PublicDomain, AllRightsReserved, OtherLicense
CallStack (from HasCallStack):
  error, called at src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs:38:62 in cabal2nix-2.9.2-3Ov8Inn3Kbg3imbyfO8PUw:Distribution.Nixpkgs.Haskell.FromCabal.License
hackage2nix: thread blocked indefinitely in an MVar operation
```

The stack is not too helpful, but on simple grepping there is no concurrent code directly inside the `cabal2nix` repo.

**Comment by Profpatsch** [comment]
Uh, I was a bit out of it yesterday. Here’s the version info:

```
nixpkgs commit: ee1faf5881aeb0d1c17c4fd1e1882d5281ab1bef
cabal2nix/hackage2nix: 2.9.2
```

I tried to build `cabal2nix` from a git checkout with cabal (inside `nix-shell -p "haskellPackages.ghcWithPackages (h: with h; [ cabal-install ])" openssl`), but I get rather strange errors:

```
$ cabal build
Preprocessing library for cabal2nix-2.9.2..
Building library for cabal2nix-2.9.2..
[11 of 17] Compiling Distribution.Nixpkgs.Haskell.BuildInfo ( src/Distribution/Nixpkgs/Haskell/BuildInfo.hs, dist/build/Distribution/Nixpkgs/Haskell/BuildInfo.o )

<no location info>: error:
    <command line>: can't load .so/.DLL for: libcrypto.so (libcrypto.so: cannot open shared object file: No such file or directory)
```

There is no reference to `libcrypto.so` inside `BuidInfo.hs`.

**Comment by peti** [comment]
Note the error message:

> fromCabalLicense: unknown licenseUnknownLicense "CC0-1.0"

I think this issue was fixed in 5b271abdcc771da46dc45ca781788c73c0b3dd9f.

**Comment by Profpatsch** [comment]
Wait, but that’s a pure function, right? As far as I can see you aren’t using concurrent code (at least in this package). Isn’t it a concurrency bug in a dependency then?

**Comment by peti** [comment]
The parallelism is introduced at https://github.com/NixOS/cabal2nix/blob/master/hackage2nix/Main.hs#L131. What happens is that the main loop computes *n* pure values concurrently, but one of those values doesn't arrive (because the function that is supposed to provide it fails with an error). This means that there is code trying to read *n* separate values from an `MVar`, but only *n-1* references to that `MVar` exist that could possibly write to it. This error is detected and the whole construct shuts down with an error.

In other worlds, the `MVar` error you see is a consequence of the parser error that happened before.

**Comment by Profpatsch** [comment]
Ah, hm, should we restructure it to something that is wrapped into some kind of error type, to get a more local error message?

**Comment by peti** [comment]
I don't understand what you mean. You *got* a local error message, no?

**Comment by Profpatsch** [comment]
I wasn’t able to make the jump from the error messages to the deadlock, but they are local in a way, yes.
