### ISSUE TITLE
Maintain hardcoded build tool dependency mapper

### ISSUE THREAD

**Issue by domenkozar** [NixOS/cabal2nix#356]
See https://github.com/commercialhaskell/stack/pull/4132/files#diff-9fe1770b08b2871a8d3e3e229168b13dR725

**Comment by peti** [comment]
Don't we have that already?

https://github.com/NixOS/cabal2nix/blob/master/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs#L177-L192
