### ISSUE TITLE
PostProcess.replace doesn't work

### ISSUE THREAD

**Issue by basvandijk** [NixOS/cabal2nix#364]
The following output is unexpected:

```
$ cabal2nix cabal://opencv
{ ... opencv, ... }:
...
  libraryPkgconfigDepends = [ opencv ];
...
```

because [we replace `opencv` with `opencv3` in PostProcess.hs](https://github.com/NixOS/cabal2nix/blob/01bd5bcbcce5343ff96ff0c54bc96228cdec86be/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs#L345).

The problem seems to be in the [replace](https://github.com/NixOS/cabal2nix/blob/01bd5bcbcce5343ff96ff0c54bc96228cdec86be/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs#L193) function. If we add a trace like:

```haskell
replace :: Binding -> Binding -> Set Binding -> Set Binding
replace old new bs =
    traceShow (old, new, bs) $
    if old `Set.member` bs then Set.insert new (Set.delete old bs) else bs
```

and run the command again we see the following output (formatted for readability):

```
$ cabal2nix cabal://opencv
( Bind (Identifier "opencv")  (Path [Identifier "pkgs",Identifier "opencv"])
, Bind (Identifier "opencv3") (Path [Identifier "pkgs",Identifier "opencv3"])
, fromList [Bind (Identifier "opencv") (Path [Identifier "null"])]
)
```

So `opencv` doesn't get replaced because its fully qualified name is `null.opencv` while we're looking for `pkgs.opencv`. I guess the problem is with the `null.opencv`. Shouldn't that binding look more like:

```
Bind (Identifier "opencv") (Path [Identifier "opencv"]
``` 
?

Note that the same problem occurs for other packages that use the `replace` function. For exampe: `cabal2nix cabal://hslua`.

**Comment by peti** [comment]
Oops. I'll fix this tomorrow (and I'll add a regression test, too).
