### ISSUE TITLE
hackage2nix instructions

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/cabal2nix#365]
I am trying to go through the instructions for hackage2nix.
I do not have have a Haskell environment installed on my NixOS system, so I am trying to determine the packages needed for a `nix-shell`.

```
git clone git@github.com:NixOS/cabal2nix.git
cd cabal2nix
git clone git@github.com:NeQuissimus/nixpkgs.git
git clone git@github.com:commercialhaskell/all-cabal-hashes.git --branch hackage hackage
```

These are fine, naturally.

Then I try to determine the equivalent for `cabal install`:

```bash
λ nix-shell -p cabal-install -p haskell.compiler.ghc843 -p zlib -p openssl --command "cabal install"                                                        1 ↵
Resolving dependencies...
Configuring cabal2nix-2.10.2...
Building cabal2nix-2.10.2...
Failed to install cabal2nix-2.10.2
Build log ( /home/nequi/.cabal/logs/ghc-8.4.3/cabal2nix-2.10.2-53T0DRZXQVMIY8MvLllRtW.log ):
cabal: Entering directory '.'
Configuring cabal2nix-2.10.2...
Preprocessing library for cabal2nix-2.10.2..
Building library for cabal2nix-2.10.2..
[ 2 of 17] Compiling Distribution.Nixpkgs.Haskell.BuildInfo ( src/Distribution/Nixpkgs/Haskell/BuildInfo.hs, dist/build/Distribution/Nixpkgs/Haskell/BuildInfo.o )
<command line>: can't load .so/.DLL for: libz.so (libz.so: cannot open shared object file: No such file or directory)
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
cabal2nix-2.10.2-53T0DRZXQVMIY8MvLllRtW failed during the building phase. The
exception was:
ExitFailure 1
```

The error looks a little like #32 but I doubt the compiler bug is back?!

Could you help me understand what I am doing wrong? Thank you!

System info:

 - system: `"x86_64-linux"`                                       
 - host os: `Linux 4.17.10, NixOS, 18.09.git.3fd0316 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
 - channels(nequi): `"stable-18.03.132915.d6c6c7fcec6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by basvandijk** [comment]
@NeQuissimus instead of `nix-shell -p cabal-install ...` you can do:
`nix-shell ./nixpkgs  -A haskellPackages.cabal2nix.env --command "cabal configure; cabal install"`
that works for me.

**Comment by NeQuissimus** [comment]
@basvandijk This does require `cabal-install` is already in the environment, because you cannot summon it with `-p cabal-install` in the `nix-shell` command (cannot combine `-A` and `-p` as per NixOS/nix#955)

It also does not work for me :(

```
Resolving dependencies...
Configuring cabal2nix-2.10.2...
Resolving dependencies...
In order, the following will be installed:
cabal2nix-2.10.2 (reinstall) (changes: monad-par-0.3.4.8 added,
monad-par-extras-0.3.3 added, mtl-2.2.2 added)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring cabal2nix-2.10.2...
Building cabal2nix-2.10.2...
Failed to install cabal2nix-2.10.2
Build log ( /home/nequi/.cabal/logs/ghc-8.4.3/cabal2nix-2.10.2-Hssrqji0tyvJ7kmmMN5XP4.log ):
cabal: Entering directory '.'
Configuring cabal2nix-2.10.2...
Preprocessing library for cabal2nix-2.10.2..
Building library for cabal2nix-2.10.2..
[ 1 of 17] Compiling Distribution.Nixpkgs.Fetch ( src/Distribution/Nixpkgs/Fetch.hs, dist/build/Distribution/Nixpkgs/Fetch.o )
Failed to load interface for ‘Data.DList’
There are files missing in the ‘dlist-0.8.0.4’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
cabal2nix-2.10.2-Hssrqji0tyvJ7kmmMN5XP4 failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by peti** [comment]
Using `-p zlib -p openssl` to bring system libraries into scope does not work. The patched ghc-wrapper from Nixpkgs might honor these flags, but Cabal does not. Check out https://github.com/basvandijk/nix-workshop/blob/master/03-finding-system-libraries/run.sh#L19-L21 for various alternative solutions that work better.

**Comment by carlosdagos** [comment]
> Using `-p zlib -p openssl` to bring system libraries into scope does not work.

This actually worked for me on macOS but not on NixOS.
