### ISSUE TITLE
extra-libraries names can disagree with package names

### ISSUE THREAD

**Issue by nh2** [NixOS/cabal2nix#378]
Follow-up from #372, there is a new problem: Even with the upstream fix we get:

```
error: anonymous function at /home/niklas/src/haskell/static-haskell-nix/static-stack/stack.nix:41164:10 called with unexpected argument 'yaml', at /nix/store/5nj7vgd7spdcvxs47gpv58nqjs76vsla-source/pkgs/development/haskell-modules/make-package-set.nix:88:27
```

I think this is because we have `extra-libraries: yaml` (which I think  is the right way  to do it), but `cabal2nix` adds that as a system dependency on `yaml` than the correct `libyaml`.

Before this didn't occur because https://github.com/NixOS/cabal2nix/commit/db540bcfa0dc67db70e947fb81ae0580011534ef called it `libyaml` manually.

**Comment by peti** [comment]
This issue has been fixed in 67e3189f683ed0b77bf3359c55bcc040c28fa194 by adding a name mapping from `yaml` to `libyaml`. I'll release cabal2nix 2.11.1 to make sure you have that new version.

**Comment by nh2** [comment]
@peti Is there a way we can make this more automatic, vs maintaining an explicit mapping?

Or should we perhaps move such mapping to nixpkgs, as technically that's the place that knows that `libyaml` and `yaml-0.1` are the same things?

**Comment by CMCDragonkai** [comment]
I just met the same kind of problem: https://stackoverflow.com/questions/55556184/finding-foreign-library-with-cabal-using-nix-shell

If I write `libmnl` in my `package.yaml`, Nix fetchs it correctly, but then cabal fails to configure complaining that it cannot find `libmnl`. But if I change it to `mnl` in `package.yaml`, cabal successfully compiles, but then Nix fails to find the `mnl` package.
