### ISSUE TITLE
fail to build on Mojave

### ISSUE THREAD

**Issue by pshemass** [NixOS/cabal2nix#385]
I was trying to install cabal2nix with `nix-env -iA nixpkgs.haskellPackages.cabal2nix. I'm using OSX Mojave with fresh Nix installation. 

here is an error: 

`In file included from lib/osxcode.cpp:30:
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:140:81: error: expected function body after function declarator
CFBundleRef _CFBundleCreateUnique(CFAllocatorRef allocator, CFURLRef bundleURL) API_AVAILABLE(macos(10.11), ios(9.0), watchos(2.0), tvos(9.0));
                                                                                ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:146:84: error: expected function body after function declarator
CFBundleRef _CFBundleCreateIfMightBeBundle(CFAllocatorRef allocator, CFURLRef url) API_DEPRECATED("Use CFBundleCreate instead", macos(10.6,10.10), ios(2.0,8.0), watchos(2.0,2.0), tvos(9.0,9.0));
                                                                                   ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:156:59: error: expected function body after function declarator
CFURLRef _CFBundleCopyResourceForkURL(CFBundleRef bundle) API_AVAILABLE(macos(10.0)) API_UNAVAILABLE(ios, watchos, tvos);
                                                          ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:194:175: error: expected function body after function declarator
CF_EXPORT CFStringRef CFBundleCopyLocalizedStringForLocalization(CFBundleRef bundle, CFStringRef key, CFStringRef value, CFStringRef tableName, CFStringRef localizationName) API_AVAILABLE(macos(10.10), ios(8.0), watchos(2.0), tvos(9.0));
                                                                                                                                                                              ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:222:52: error: expected function body after function declarator
Boolean _CFBundleGetHasChanged(CFBundleRef bundle) API_DEPRECATED("Function no longer supported", macos(10.0,10.13), ios(2.0,11.0), watchos(2.0,4.0), tvos(9.0,11.0));
                                                   ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:225:33: error: expected function body after function declarator
void _CFBundleFlushCaches(void) API_DEPRECATED("Function no longer supported", macos(10.0,10.8), ios(2.0,6.0), watchos(2.0,2.0), tvos(9.0,9.0));
                                ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:228:47: error: expected function body after function declarator
void _CFBundleFlushCachesForURL(CFURLRef url) API_DEPRECATED("Function no longer supported", macos(10.0,10.8), ios(2.0,6.0), watchos(2.0,2.0), tvos(9.0,9.0));
                                              ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:255:59: error: expected function body after function declarator
CFStringRef _CFDoubledStringCreate(CFStringRef theString) API_AVAILABLE(macosx(10.13), ios(11.0), watchos(4.0), tvos(11.0));
                                                          ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:258:63: error: expected function body after function declarator
CFStringRef _CFAccentuatedStringCreate(CFStringRef theString) API_AVAILABLE(macosx(10.13), ios(11.0), watchos(4.0), tvos(11.0));
                                                              ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:261:99: error: expected function body after function declarator
CFStringRef _CFAffixedStringCreate(CFStringRef theString, CFStringRef prefix, CFStringRef suffix) API_AVAILABLE(macosx(10.13), ios(11.0), watchos(4.0), tvos(11.0));
                                                                                                  ^
/nix/store/8v9xplbvxm2ddxv4nhbj21iryb4vmbjc-swift-corefoundation-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBundlePriv.h:264:66: error: expected function body after function declarator
CFStringRef _CFRLORightToLeftStringCreate(CFStringRef theString) API_AVAILABLE(macosx(10.13), ios(11.0), watchos(4.0), tvos(11.0));
                                                                 ^
17 warnings and 11 errors generated.`

**Comment by peti** [comment]
This error is clearly not related to `cabal2nix`. The tool contains no file `lib/osxcode.cpp`.

**Comment by pshemass** [comment]
@peti should I create issue in Nix that this file is missing? what should be next step to solve that?

**Comment by peti** [comment]
Note that here is no missing file. Some package does not compile on your system and that's totally unrelated to cabal2nix. I don't know what the issue is since I don't have enough information to guess even. A good place to report this issue might be https://github.com/nixos/nixpkgs.
