### ISSUE TITLE
generate haddocks for the haskell-gi family of packages

### ISSUE THREAD

**Issue by cdepillabout** [NixOS/cabal2nix#386]
A couple years ago there was a commit that disabled building haddocks for packages that contain no visible modules: https://github.com/NixOS/cabal2nix/issues/45 (in particular https://github.com/NixOS/cabal2nix/commit/ea90238ed2fc3fd04c01e0fa7b80842f92cf410d)

However, there are some packages that can generate modules dynamically from the `Setup.hs` file, even though they appear to contain no visible modules if you only look at the `.cabal` file.  These are the `haskell-gi` family of libraries.

For instance, take [`gi-vte`](http://hackage.haskell.org/package/gi-vte).  The `gi-vte.cabal` file defines no modules:

http://hackage.haskell.org/package/gi-vte-2.91.19/gi-vte.cabal

Instead, a bunch of modules are generated from the `Setup.hs` file:

http://hackage.haskell.org/package/gi-vte-2.91.19/src/Setup.hs
https://hackage.haskell.org/package/gi-vte-2.91.19/docs/GI-Vte.html

Other libraries that use this same technique:

- [`gi-gdk`](https://hackage.haskell.org/package/gi-gdk)
- [`gi-gio`](https://hackage.haskell.org/package/gi-gio)
- [`gi-glib`](https://hackage.haskell.org/package/gi-glib)
- [`gi-gtk`](https://hackage.haskell.org/package/gi-gtk)
- [`gi-pango`](https://hackage.haskell.org/package/gi-pango)

I'd like to either remove the check from https://github.com/NixOS/cabal2nix/commit/ea90238ed2fc3fd04c01e0fa7b80842f92cf410d that doesn't run haddocks on libraries that expose no modules, OR add a special case for haskell-gi libraries.

Would a PR be accepted for either one?

I've confirmed that actually building documentation for the libraries listed above works.  I am currently [doing this](https://github.com/cdepillabout/termonad/blob/a344053ade1a4fee7f64f805d92a9a684c3ef133/.nix-helpers/nixpkgs.nix#L62-L68) for my [termonad](https://github.com/cdepillabout/termonad) project.

**Comment by peti** [comment]
The best way to accomplish this is to add post-processing hooks into https://github.com/NixOS/cabal2nix/blob/master/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs#L72-L73 that `set runHaddock True` for the appropriate packages (and appropriate versions of those packages).

**Comment by peti** [comment]
400a9eb556b11aa4ab3b6d0bc5eeb963a4f63e4f has the updated Haskell package set. I'll merge the new versions to `master` soon.

**Comment by cdepillabout** [comment]
Thanks a lot!  That was fast!
