### ISSUE TITLE
update-nixpkgs.sh second time fails with "attribute 'Cabal_2_4_0_1' missing"

### ISSUE THREAD

**Issue by cyounkins** [NixOS/cabal2nix#391]
If I follow the instructions in the README:
```
git clone git@github.com:NixOS/cabal2nix.git
cd cabal2nix
git clone git@github.com:NixOS/nixpkgs.git
git clone git@github.com:commercialhaskell/all-cabal-hashes.git --branch hackage hackage
cabal install
./update-nixpkgs.sh
```

It will work once (it gets to pushing the commit), but the second time I run `./update-nixpkgs.sh` it fails with:
```
[nix-shell:~/cabal2nix]# ./update-nixpkgs.sh
Up to date
creating /root/cabal2nix/dist-newstyle/build
creating /root/cabal2nix/dist-newstyle/tmp
Selecting cabal2nix-2.12-inplace-hackage2nix to supply hackage2nix
/root/cabal2nix/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal2nix-2.12/x/hackage2nix/build/hackage2nix/hackage2nix '--nixpkgs=/root/cabal2nix/nixpkgs' '+RTS' -M4G -RTS
error: attribute 'Cabal_2_4_0_1' missing, at /root/cabal2nix/nixpkgs/pkgs/development/haskell-modules/configuration-common.nix:36:77
(use '--show-trace' to show detailed location information)
hackage2nix: user error (Error in $: not enough input)
*** error 1: cabal -v2 new-run hackage2nix -- --nixpkgs="$PWD/nixpkgs" +RTS -M4G -RTS
```

The environment I'm running in is from `nix-shell -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.hackage2nix pkgs.abstract-par pkgs.hopenssl pkgs.zlib ])"`

Any suggestions would be appreciated!

**Comment by peti** [comment]
The first update replaced `Cabal_2_4_0_1` by the new version `Cabal_2_4_1_0`. This means that some overrides in Nixpkgs need to be adapted for the new version to fix evaluation. This particular issue was fixed in https://github.com/NixOS/nixpkgs/commit/b13d8eadaaa42195688366a1a12d1c39465d927c. If you use the new version of `master` or `haskell-updates`, this error will no longer occur.

**Comment by cyounkins** [comment]
Thank you @peti !
