### ISSUE TITLE
Should cabal2nix handle vty vs vty_5_25_1?

### ISSUE THREAD

**Issue by stites** [NixOS/cabal2nix#392]
When trying to write a shell file for [glguy/irc-core](https://github.com/glguy/irc-core) and cabal new-build, I found that there is a failed dependency match where vty must be >= 5.23.1 and < 5.26. Nixpkgs supplies two vtys (`vty` and `vty_5_25_1`) so I had to manually update the default.nix in order to get this project to build.

This is also breaking the autogenerated derivation at `nixpkgs`, so you can see this immediately when you install glirc with `nix-env -f "<nixpkgs>" -iA "haskellPackages.glirc"`.

**Comment by peti** [comment]
Yes, that version choice must be made manually, `cabal2nix` can't do that automatically.
