### ISSUE TITLE
How to use cabal 2.4?

### ISSUE THREAD

**Issue by JulianAntonielli** [NixOS/cabal2nix#399]
I'm trying to use `cabal2nix` with cabal 2.4, and I get `proj.cabal:0:0: Unsupported cabal-version. See https://github.com/haskell/cabal/issues/4899.`

I'm not yet clear after reading the issue if cabal 2.4 is unsupported or not.

Any pointers? Thanks

**Comment by jjant** [comment]
The error is gotten after creating a fresh project with `cabal 2.4.1.0`, and running `cabal2nix .` (version `2.12`) from terminal. In case it helps, this is using `nix 2.1.3`.

**Comment by peti** [comment]
`cabal2nix` uses `Cabal` for reading & parsing the file. So whatever formats your version of `Cabal` supports, `cabal2nix` supports as well.

**Comment by jjant** [comment]
@peti Sorry, but that's not a really useful answer, this cabal file was created by Cabal itself, and it parses it correctly, `cabal2nix` doesn't.

**Comment by peti** [comment]
Then you are using an old version of `cabal2nix` that was not linked to a sufficiently recent version of `Cabal`.

**Comment by jjant** [comment]
Again, it's using the latest 2.12 version, just reproduced the problem with a fresh project. Old cabal (1.10 for example) works fine.

**Comment by peti** [comment]
Can you please show me a cut&paste log of the exact command line you use to call `cabal2nix` and the output it generates in response?

**Comment by basvandijk** [comment]
You can also try using `cabal2nix` from a recent `nixpkgs` checkout like:

```
nix-shell -E \
  'let nixpkgs = builtins.fetchTarball { 
         url = https://github.com/NixOS/nixpkgs/archive/8dddd6d4a1a276e00501595f19d6eaaede41c1b1.tar.gz; 
         sha256 = "0gksmb59q0yfys841gfxwgzkw0zr8zc0vkv911xyl1sf62bvmbfa"; 
       }; 
       pkgs = import nixpkgs {}; 
   in pkgs.myEnvFun { 
        name = "cabal2nix-env"; 
        buildInputs = [ pkgs.cabal2nix ]; 
      }'
```

Note that [`cabal2nix` is based on `haskellPackages.cabal2nix`](https://github.com/NixOS/nixpkgs/blob/8dddd6d4a1a276e00501595f19d6eaaede41c1b1/pkgs/top-level/all-packages.nix#L1096) and [`haskellPackages` is using GHC-8.6.3](https://github.com/NixOS/nixpkgs/blob/8dddd6d4a1a276e00501595f19d6eaaede41c1b1/pkgs/top-level/all-packages.nix#L7036) and [GHC-8.6.3 comes with `Cabal-2.4.0.1`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/8.6.1-notes.html#included-libraries). So I believe using a recent nixpkgs would fix your problem.
