### ISSUE TITLE
cabal2nix doesn't add `build-tools` to derivation

### ISSUE THREAD

**Issue by chessai** [NixOS/cabal2nix#401]
for example, in a cabal file, specifying `build-tools: hsc2hs` has no effect, even though this seems like it should be a build dependency. This came up just now when I was trying to override hsc2hs, and had to use haskell.lib.addBuildDepend. this can be reproduced by adding that line to any `library` or `executable` stanza in a cabal file, and looking at the output.

**Comment by peti** [comment]
`cabal2nix` *does* add build-tools into the generated output. It will not add `hsc2hs` as a dependency, however, because that tool is a part of the `ghc` compiler and it's always available in the Nix build environment.
