### ISSUE TITLE
How to prevent Hackage packages shaddowing system packages (build-tools)

### ISSUE THREAD

**Issue by luke-clifton** [NixOS/cabal2nix#407]
Is there a clever way to do this?

**Comment by luke-clifton** [comment]
Cabal says that this field is to be used by told available on hackage only. The fact that it works with system packages at all is perhaps the real big... But I like that behaviour. Closing.

**Comment by peti** [comment]
Generally speaking, we cannot auto-detect all required build inputs automatically. The Cabal file syntax is ambiguous, unfortunately. There have been improvements recently (https://cabal.readthedocs.io/en/latest/developing-packages.html?highlight=build-tools#pkg-field-build-tool-depends), but those improvements fail to address the case where Haskell packages depend on system executables that are not written in Haskell. It's still WIP in suppose.
