### ISSUE TITLE
hpack should be ran before jailbreak

### ISSUE THREAD

**Issue by domenkozar** [NixOS/cabal2nix#421]
Otherwise jailbreak fails to find a cabal file.

hpack runs in `preConfigure`, jailbreak in `postPatch`. Maybe hpack should run in `prePatch`?

**Comment by peti** [comment]
The change is extremely simple to make: https://github.com/NixOS/cabal2nix/blob/master/src/Cabal2nix.hs#L196. Do you have the chance to test whether moving the `hpack` call to `prePatch` actually fixes the problem? I'll be happy to merge a PR to that effect.

**Comment by domenkozar** [comment]
@turbomack do you want give this one a go? :)

**Comment by turboMaCk** [comment]
Sure. I can test it on this case https://github.com/NixOS/nixpkgs/pull/62899#discussion_r292182330

**Comment by peti** [comment]
Fixed in https://hackage.haskell.org/package/cabal2nix-2.14.4.

**Comment by turboMaCk** [comment]
thanks, @peti we all very appreciate the time you put into maintaining this project :+1:
