### ISSUE TITLE
cabal2nix output NoHackageTarballFound for all cabal://xxx

### ISSUE THREAD

**Issue by MarisaKirisame** [NixOS/cabal2nix#423]
I tried running the following command on my nixos:
> nix-shell -p "cabal2nix" --run "cabal2nix cabal://mtl"

I get this output:
> cabal2nix: NoHackageTarballFound

what is happening here?

**Comment by peti** [comment]
You should probably run `cabal v2-update` to make the Hackage tarball available in `~/.cabal`.

**Comment by gregor-alexandru** [comment]
I get following issue when I try to run `cabal v2-update`:
```
newParallelJobControl: not a sensible number of jobs: 0
CallStack (from HasCallStack):
  error, called at ./Distribution/Client/JobControl.hs:101:3 in main:Distribution.Client.JobControl
```
