### ISSUE TITLE
cabal2nix 2.14.4 fails to compile against distribution-nixpkgs >= 1.3

### ISSUE THREAD

**Issue by cumber** [NixOS/cabal2nix#430]
[distribution-nixpkgs 1.2](https://hackage.haskell.org/package/distribution-nixpkgs-1.2/docs/Language-Nix-PrettyPrinting.html) re-exports [`disp` from Cabal's Distribution.Text](https://hackage.haskell.org/package/Cabal-2.4.1.0/docs/Distribution-Text.html).

`distribution-nixpkgs` 1.3 removed the re-export (presumably to be compatible with `Cabal` 3.0, which doesn't have `disp` anymore), which breaks `cabal2nix`; I get this error:

```
src/Distribution/Nixpkgs/Haskell/Derivation.hs:115:41: error:
    Variable not in scope: disp :: PackageName -> Doc
    |
115 |       [ attr "pname"   $ doubleQuotes $ disp (packageName _pkgid)
    |                                         ^^^^

src/Distribution/Nixpkgs/Haskell/Derivation.hs:116:41: error:
    Variable not in scope:
      disp :: Distribution.Types.Version.Version -> Doc
    |
116 |       , attr "version" $ doubleQuotes $ disp (packageVersion _pkgid)
    |                                         ^^^^
```

Unfortunately `cabal2nix` 2.14.4, `distribution-nixpkgs` 1.3.0, and `Cabal` 2.4.0.1 is currently the combination live on the unstable branch of nixpkgs, so `cabal2nix` doesn't build but adding an upper bound on `distribution-nixpkgs` would fix the problem for a build from Hackage but not from nixpkgs.

**Comment by peti** [comment]
Nixpkgs `master` has version 2.15.0 and as far I know it builds fine.

**Comment by peti** [comment]
I thought about adding the proper upper bound on Hackage, too, but I reckon that I would have to add that to great many versions of  `cabal2nix`, which feels like it would be too great an effort now that the newer version is out anyways.
