### ISSUE TITLE
zlib issue in cabal2nix

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/cabal2nix#437]
When using cabal2nix, with a package.yaml listing `zlib` as the `extra-libraries`. It generates a nix file like so:

```
{ mkDerivation, amazonka, amazonka-core, amazonka-ec2, amazonka-s3
, base, bytestring, containers, filepath, hpack, lens
, neat-interpolation, stdenv, stm, text, typed-process, utf8-string
, zlib
}:
mkDerivation {
  pname = "node-construction-prototype";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    amazonka amazonka-core amazonka-ec2 amazonka-s3 base bytestring
    containers filepath lens neat-interpolation stm text typed-process
    utf8-string
  ];
  librarySystemDepends = [ zlib ];
  libraryToolDepends = [ hpack ];
  executableHaskellDepends = [
    amazonka amazonka-core amazonka-ec2 amazonka-s3 base bytestring
    containers filepath lens neat-interpolation stm text typed-process
    utf8-string
  ];
  executableSystemDepends = [ zlib ];
  testHaskellDepends = [
    amazonka amazonka-core amazonka-ec2 amazonka-s3 base bytestring
    containers filepath lens neat-interpolation stm text typed-process
    utf8-string
  ];
  testSystemDepends = [ zlib ];
  prePatch = "hpack";
  homepage = "https://github.com/N/A#readme";
  license = stdenv.lib.licenses.asl20;
}
```

Running `cabal v1-configure` in a nix-shell using the above derivation `.env` results in:

```
cabal: Missing dependencies on foreign libraries:
* Missing (or bad) C libraries: zlib, zlib
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
the library files do exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
```

**Comment by CMCDragonkai** [comment]
This happens even if we provide `zlib` in the `buildInputs` explicitly in the `shell.nix`.

**Comment by peti** [comment]
The build needs the *system library* `zlib` -- a.k.a. `pkgs.zlib`. Make sure you pass that one, *not* the Haskell library `haskellPackages.zlib` which is in scope by default for Haskell's `mkDerivation` function but won't work.

**Comment by CMCDragonkai** [comment]
How do we ensure that in package.yaml? Or are we meant to override the generated default.nix?

Is this the policy whenever there's a name conflict between haskell packages and top level packages?

On 31 December 2019 07:52:12 GMT+11:00, Peter Simons <notifications@github.com> wrote:
>The build needs the *system library* `zlib` -- a.k.a. `pkgs.zlib`. Make
>sure you pass that one, *not* the Haskell library
>`haskellPackages.zlib` which is in scope by default for Haskell's
>`mkDerivation` function but won't work.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/cabal2nix/issues/437#issuecomment-569793247

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
@peti It still doesn't work even if I override what `zlib` is. I tried it with:

```
{ pkgs ? import ./pkgs.nix }:

with pkgs;
let
  haskellPackages = haskell.packages.ghc865;
  drv = (haskellPackages.callPackage ./default.nix {
    zlib = pkgs.zlib;
  }).env;
in
  drv.overrideAttrs (attrs: {
    src = null;
    nativeBuildInputs = attrs.nativeBuildInputs ++ (with haskellPackages; [
      cabal-install
      cabal2nix
      hpack
    ]);
    shellHook = attrs.shellHook + ''
      echo 'Entering ${attrs.name}'
      set -v

      cabal2nix --hpack . >./default.nix
      hpack --force
      cabal v1-configure

      set +v
    '';
  })
```

I also tried with `zlib = pkgs.zlib.dev;`.

The `cabal v1-configure` still responds with:

```
Configuring node-construction-prototype-0.1.0.0...
cabal: Missing dependencies on foreign libraries:
* Missing (or bad) C libraries: zlib, zlib
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
the library files do exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
```

**Comment by CMCDragonkai** [comment]
If I switch on verbose mode, I can see these logs at the very end of `cabal v1-configure`:

```
/nix/store/47hi526v96skkwgdj7d9c31ccd1xivrx-gcc-wrapper-8.3.0/bin/cc returned
ExitFailure 1 with error message:
/nix/store/m8ih8gw7qnd2c7p0qgv3cn4b6abkbanb-binutils-2.31.1/bin/ld: cannot
find -lzlib
collect2: error: ld returned 1 exit status
/nix/store/47hi526v96skkwgdj7d9c31ccd1xivrx-gcc-wrapper-8.3.0/bin/cc -fno-stack-protector /tmp/894-12.c -o /tmp/894-13 -c '-D__GLASGOW_HASKELL__=806' '-Dlinux_BUILD_OS=1' '-Dx86_64_BUILD_ARCH=1' '-Dlinux_HOST_OS=1' '-Dx86_64_HOST_ARCH=1' -Idist/build/autogen -I. -I/nix/store/ncgs0wwqrch4adppy0d2nqb92li2whbh-zlib-1.2.11-dev/include -I/nix/store/qimay8q401gpgcavj617zp68p3ilwsa5-ghc-8.6.5/lib/ghc-8.6.5/process-1.6.5.0/include -I/nix/store/377rpwbqripx92lwwpp406np3r9md60p-network-2.8.0.1/lib/ghc-8.6.5/x86_64-linux-ghc-8.6.5/network-2.8.0.1-Hmt657UE3v349uYmvUXEvW/include -I/nix/store/rasrifs89nf2qpj13lb92mp8k4n62rm9-vector-algorithms-0.8.0.3/lib/ghc-8.6.5/x86_64-linux-ghc-8.6.5/vector-algorithms-0.8.0.3-DATDeXPuJicHFnHtLbmnOb/include -I/nix/store/bzdynilkj4v4qc44q90cl13bz2rl8pdy-vector-0.12.0.3/lib/ghc-8.6.5/x86_64-linux-ghc-8.6.5/vector-0.12.0.3-2LEYu9M2i7lERDtz76XG3n/include -I/nix/store/qimay8q401gpgcavj617zp68p3ilwsa5-ghc-8.6.5/lib/ghc-8.6.5/unix-2.7.2.2/include -I/nix/store/qimay8q401gpgcavj617zp68p3ilwsa5-ghc-8.6.5/lib/ghc-8.6.5/time-1.8.0.2/include -I/nix/store/5ldzwhqrvzwp0ffnib3d6xs9r7whj8nx-primitive-0.6.4.0/lib/ghc-8.6.5/x86_64-linux-ghc-8.6.5/primitive-0.6.4.0-ILgywxtLpvnAOlEISPpP5b/include -I/nix/store/qimay8q401gpgcavj617zp68p3ilwsa5-ghc-8.6.5/lib/ghc-8.6.5/bytestring-0.10.8.2/include -I/nix/store/qimay8q401gpgcavj617zp68p3ilwsa5-ghc-8.6.5/lib/ghc-8.6.5/base-4.12.0.0/include -I/nix/store/50zhcascvlj4xi5gdcxk83cvwvgs1p4l-gmp-6.1.2-dev/include -I/nix/store/qimay8q401gpgcavj617zp68p3ilwsa5-ghc-8.6.5/lib/ghc-8.6.5/integer-gmp-1.0.2.0/include -I/nix/store/qimay8q401gpgcavj617zp68p3ilwsa5-ghc-8.6.5/lib/ghc-8.6.5/include -I/nix/store/7mb6jm8dqbg7viq5gh0yk1fl8a6v9jbm-libffi-3.3-dev/include
CallStack (from HasCallStack):
  die', called at ./Distribution/Simple/Configure.hs:1879:34 in Cabal-3.0.0.0-CD1INMNwoxXIKVgcu1nec5:Distribution.Simple.Configure
  checkForeignDeps, called at ./Distribution/Simple.hs:643:7 in Cabal-3.0.0.0-CD1INMNwoxXIKVgcu1nec5:Distribution.Simple
cabal: Missing dependencies on foreign libraries:
* Missing (or bad) C libraries: zlib, zlib
```

**Comment by CMCDragonkai** [comment]
Hmm I tried all sorts of variants, still can't get it to work. Maybe something changed in Nixpkg's zlib? No matter what cabal just cannot find `zlib`...

**Comment by peti** [comment]
System dependencies are not discovered automatically by `configure` in an `nix-shell` environment. That happens only when *building* packages, not in the interactive environment. There, you need to pass appropriate flags to `conffigure` to make sure the library is found. See https://github.com/basvandijk/nix-workshop/tree/master/03-finding-system-libraries for several examples.

**Comment by CMCDragonkai** [comment]
Zlib also isn't found during nix-build though.

**Comment by peti** [comment]
Where can I find your source code?

**Comment by CMCDragonkai** [comment]
Here I've created one just now: https://github.com/MatrixAI/Haskell-Demo-Zlib

Try `nix-shell` then `cabal v2-build`.

OR

```
nix-build ./release.nix -A library
```

See that `release.nix` and `shell.nix` have overridden the `zlib` to be `pkgs.zlib`.

**Comment by CMCDragonkai** [comment]
@peti after some playing around, it turns out that I don't actually need `zlib` at all.

So things are fine by removing `zlib` entirely.

However let's say for example I did in fact have haskell code needing to bind into the `zlib` library.

Does this mean using `extra-libraries` in package.yaml is incorrect? Or is something different/wrong with `pkgs.zlib`. Because surely that specifying it in `package.yaml` shouldn't create such consternation!

**Comment by eyeinsky** [comment]
@CMCDragonkai I'm no expert, but [in your code](https://github.com/MatrixAI/Haskell-Demo-Zlib/blob/master/shell.nix#L6-L8) I think you are mixing the operating system's package and the haskell package with the same name. You don't need to override or depend on the haskell package -- what you needs is for the system's zlib library to be available to the linker.

I'm running nixos and was struggling with the same issue just when building a (plain) stack package. Turns out I needed to add the nix section to stack.yaml, as outlined [here](https://nixos.org/nixpkgs/manual/#builds-using-stack-complain-about-missing-system-libraries). Your situation is different because your (demo) project is not stack based, but maybe you can get ideas from there.

(Previously I had tried to install zlib in various ways, including `nix-env -iA nixos.zlib.dev` which didn't help.)

**Comment by peti** [comment]
The `extra-libraries` section at https://github.com/MatrixAI/Haskell-Demo-Zlib/blob/master/package.yaml#L32-L33 expects the name of a *library*, not a package name. Just replace `zlib` with `z` and the configure phase will succeed.

**Comment by CMCDragonkai** [comment]
I didn't know that the library name was actually just `z`. Is there a place which lists the actual library names?
