### ISSUE TITLE
use stdout instead of implicitly writing to a file

### ISSUE THREAD

**Issue by hyperfekt** [NixOS/cabal2nix#454]
Hardcoding the location of the output file in <del>cabal2nix</del> hackag2nix isn't a big problem but seems like a bad practice because it makes it harder to understand what the tool is doing and to adapt its function.

**Comment by peti** [comment]
I don't understand what you mean. Cabal2nix *does* write to standard output:

~~~
$ cabal2nix cabal://hackage-db
{ mkDerivation, aeson, base, bytestring, Cabal, containers
, directory, exceptions, filepath, stdenv, tar, time, utf8-string
}:
mkDerivation {
  pname = "hackage-db";
  version = "2.1.0";
  sha256 = "7458bdecb426344ced430851c95ef5901b827e610063e6b32ba2acbc32054cef";
  revision = "1";
  editedCabalFile = "1h3x5a8xmqkkcd3h1m7z0il1vbsh2c77685y68zmyp21zb1y88hy";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson base bytestring Cabal containers directory exceptions
    filepath tar time utf8-string
  ];
  homepage = "https://github.com/peti/hackage-db#readme";
  description = "Access cabal-install's Hackage database via Data.Map";
  license = stdenv.lib.licenses.bsd3;
}
~~~

**Comment by hyperfekt** [comment]
Sorry, my mistake. I was referring to hackage2nix.

**Comment by peti** [comment]
IMHO, it's fine for `hackage2nix` to write the generated file into the Nixpkgs repository it's been run with. It might be nice to add a `-o` flag, maybe, so that users can direct that output somewhere else, but I'd rather not change the default behavior.
