### ISSUE TITLE
Better error message needed for callCabal2nix name when ${name}.cabal is missing

### ISSUE THREAD

**Issue by sorki** [NixOS/cabal2nix#472]
This is frequent source of confusion for new users and I think that `cabal2nix` should output better error message than:

```
cabal2nix: nix-prefetch-url: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

I'll take a look iff this can be fixed easily.

**Comment by sternenseemann** [comment]
This was actually fixed by <https://github.com/NixOS/cabal2nix/pull/489> which found the flaw in the fetcher logic. Sorry this took so long to notice.
