### ISSUE TITLE
Support cabal-version: 3.4

### ISSUE THREAD

**Issue by pranaysashank** [NixOS/cabal2nix#522]
with `cabal-version` field set to 3.4, cabal2nix fails with

```
*** cannot parse "././foo.cabal":
foo.cabal:0:0: Unsupported cabal-version 3.4. See https://github.com/haskell/cabal/issues/4899.
foo.cabal:0:0: Unsupported cabal-version. See https://github.com/haskell/cabal/issues/4899.

*** parsing cabal file: user error (*** Exiting.)
```

## Version
```
$ cabal2nix --version
cabal2nix 2.18.0`
```

**Comment by maralorn** [comment]
I may be wrong but isn‘t this just a matter of the Cabal library version we link against? So maybe this works with pkgs.haskell.packages.ghc901.cabal2nix?

**Comment by pranaysashank** [comment]
I think you are right. I tried this ghc 8.10.7. I'll update the issue after trying with ghc901

**Comment by sternenseemann** [comment]
@pranaysashank Did that work?

**Comment by pranaysashank** [comment]
I didn't find an easy way to test it, I couldn't override the version of cabal2nix as I kept on getting infinite recursion errors in the nix derivation when I try to change it.

**Comment by sternenseemann** [comment]
@pranaysashank just try `haskell.packages.ghc901.cabal2nix`, for example.

**Comment by pranaysashank** [comment]
> Did that work?

Yup, it's working.
