### ISSUE TITLE
‘The program 'ghc-pkg' is required but it could not be found’

### ISSUE THREAD

**Issue by bradrn** [NixOS/cabal2nix#523]
Following the instructions in https://haskell4nix.readthedocs.io/nixpkgs-users-guide.html#how-to-build-a-stand-alone-project I attempted to build my Haskell project with GHCJS. Indeed, running `nix-build` worked successfully. However, I would prefer to run `cabal` myself within `nix-shell`, but when I attempt to do this I get the following error:

```
$ cabal build
cabal: The program 'ghc-pkg' is required but it could not be found.
```

This seems odd to me… I would have thought that `ghc-pkg` should always be installed alongside `cabal`. Certainly it seems that `ghc-pkg` is nowhere to be seen on PATH:

```
$ ghc-pkg
bash: ghc-pkg: command not found
```

**Comment by cdepillabout** [comment]
@bradrn Could you show the full project (all Nix code and all Haskell code) that you are trying to build, as well as how you're trying to build on the command line?

Linking to a git repo would be very helpful.

**Comment by bradrn** [comment]
Thanks for the quick response! I’d rather not share the code, but it’s not especially interesting in any case… it’s not an especially large project (~1500 LOC at the moment). The project Nix file was generated from `cabal2nix` and has not been modified since, and the `default.nix` and `shell.nix` were copied verbatim from the documentation (only the project name was changed).

**Comment by cdepillabout** [comment]
@bradrn Without knowing the exact code you're running against, and without being able to `git clone` and poke around on the thing you're having trouble with, it is hard for anyone to help you.

> attempted to build my Haskell project with GHCJS

For instance, GHCJS was just recently re-added to Nixpkgs `haskell-updates`.  Without concrete steps to reproduce your problem, I have no idea if you are aware of this, and having trouble using it, or if you didn't know this and are trying to use GHCJS from a Nixpkgs where it is not working.

**Comment by bradrn** [comment]
> Without knowing the exact code you're running against, and without being able to `git clone` and poke around on the thing you're having trouble with, it is hard for anyone to help you.

I know, sorry… let me see if I can make a minimal reproducible example.

> For instance, GHCJS was just recently re-added to Nixpkgs `haskell-updates` … I have no idea if you are aware of this

Almost certainly not. I only started using Nix a couple of days ago, when I first tried GHCJS.

**Comment by bradrn** [comment]
Huh, interesting… after I installed `ghc8107Binary` to get `cabal init` working, everything worked fine! I can only conclude that `ghc-pkg` is distributed with GHC, there’s a missing dependency on GHC somewhere, and the only reason no-one’s found it yet is because it’s so vanishingly rare to install Cabal but not GHC.

**Comment by cdepillabout** [comment]
Yeah, in Nixpkgs `cabal-install` does not pull in GHC.  The reasoning for this is:

1. We don't know what version of GHC you want to use.  The same version of `cabal-install` can be used with multiple GHC versions.
2. Some users may want to get `cabal-install` from nixpkgs, but use GHC installed from their distro.

**Comment by bradrn** [comment]
Thanks for explaining! So it looks like if I want to use `nix-shell` with a GHCJS project, I’ll have to also add `--package ghc` manually, right?

Also, I discovered that `cabal-install` requires `pkg-config`, but doesn’t depend on that either. Is that intentional, or should I open another issue for that?
