### ISSUE TITLE
docs: Sidebar on left doesn't scroll

### ISSUE THREAD

**Issue by glasserc** [NixOS/cabal2nix#561]
On my laptop, the nav on the left side of the site at https://haskell4nix.readthedocs.io/ does not scroll. On some pages, therefore, some of the table of contents is occluded, leading to a false impression of having read all the content.

![Screenshot from 2022-07-10 14-04-15](https://user-images.githubusercontent.com/17006/178156713-6a4aac42-2a23-46bf-a35b-42f9fdff3a94.png)

It's possible to see all the content again by going back to the homepage, but you have to know that there is more content, which isn't obvious.

It seems this is due to a quirk of the Alabaster theme (https://github.com/bitprophet/alabaster/pull/114) which doesn't seem like it will be solved in the near future. Other sites have run into this too: https://github.com/esphome/issues/issues/2477, https://stackoverflow.com/questions/57031848/sphinx-alabaster-theme-scroll-inside-of-fixed-sidebar. One obvious fix might be to just disable the `fixed_sidebar` option.

**Comment by maralorn** [comment]
Thanks for pointing to that.

Our plan has been for quite a while to move away from readthedocs and put the documentation back into the nixpkgs manual.
