### ISSUE TITLE
cabal version 3.8 is unsupported

### ISSUE THREAD

**Issue by dark-ether** [NixOS/cabal2nix#596]
when creating a project via cabal init -n it generates the cabal file with the latest version of the cabal standard. when running cabal 2nix in with a cabal file generated this way it doesn't produce a nix derivation

**Comment by sternenseemann** [comment]
How have you obtained `cabal2nix`? What `cabal2nix` supports depends on which version of Cabal it is built against. I think in nixpkgs we just use the default one for the default compiler, so 3.6 for 9.2 at the moment.

**Comment by dark-ether** [comment]
ok, thank you sorry for wasting your time.

**Comment by sternenseemann** [comment]
As said, it maybe makes sense building `cabal2nix` against Cabal 3.8 in nixpkgs' default package set as well…
