### ISSUE TITLE
Support single-file Haskell script

### ISSUE THREAD

**Issue by eownerdead** [NixOS/cabal2nix#613]
With `cabal run` all dependencies will be built. However, if Nix cache can be used Haskell will become more useful for scripting language, like Python.
Also, it may be more convenient if it can be executable like `cabal2nix --run ./script.hs`.
Sorry if this is already supported or duplicated.
Regards.

* [Official Cabal document](https://cabal.readthedocs.io/en/stable/getting-started.html#run-a-single-file-haskell-script)

**Comment by sternenseemann** [comment]
You can use [`nix-shell`'s interpreter capabilities](https://nixos.org/manual/nix/stable/command-ref/nix-shell#use-as-a--interpreter) for this together with `ghcWithPackages` from nixpkgs for providing the dependencies and ghc.

**Comment by eownerdead** [comment]
But... we can't run them without Nix, need to rewrite cabal scripts, and probably can't package them.
Sorry for the late response🙏

**Comment by sternenseemann** [comment]
@eownerdead `cabal2nix` won't be able to give you a solution that works without Nix. It is merely a tool that generates Nix code. The `cabal` shebang is your best shot then.
