### ISSUE TITLE
Status of the repository?

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/cabal2nix#615]
Hi,

As part of https://github.com/NixOS/teams-collaboration/issues/1, I am trying to clarify the status of the repositories under the NixOS organisation.

This repository seems to be unmaintained or obsolete, so it will be archived in a month.

If you think it warrants staying here or should be moved to another organization instead, please answer this issue.

**Comment by ncfavier** [comment]
This repository is not unmaintained or obsolete.

**Comment by thufschmitt** [comment]
Urgh I'm sorry. I've added all the “merged into cabal2nix” repos in the list of repositories to check for status, and I accidentally added cabal2nix itself. Please ignore.
