### ISSUE TITLE
Teach cabal2nix how to generate shell.nix too

### ISSUE THREAD

**Issue by ocharles** [NixOS/cabal2nix#72]
I wrote the following little FAQ: http://wiki.ocharles.org.uk/Nix#how-do-i-use-cabal2nix-for-local-projects. I get asked this a lot, and the process is entirely mechanical - so I feel this is something that could go into `cabal2nix`.

@peti, if you agree this is useful - where would you put it?

**Comment by peti** [comment]
Implemented `--shell` flag.
